#### Importing Libraries

In [486]:
import pandas as pd
from IPython.display import display
import numpy as np
import os
import re

In [487]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Captain_Burtons/input/form_data_filtered.csv")
display(df.sample(50))

,ID,Submission Date,Organization Name,Your First Name,Last Name,Phone Number,Email Address,Desired Date & Time of Event,Address of Event,City,...,Name of Event,End Time of the Event,Street Address of Event,Event Description,Anticipated Number of Participants,First Name,Agency Name,Type of Agency,IP Address,Referrer
590,32643.0,5/18/2017 14:49,DECI,NaN,Overton,9198627033,kavanoverton@yahoo.com,6/21/2017 14:00,NaN,Durham,...,NaN,NaN,1717 E Lawson Street,NaN,240,Kavan,NaN,NaN,70.60.99.26,http://durhamnc.gov/FormCenter/Fire-Department...
2020,80639.0,4/19/2022 21:13,NaN,NaN,Peoples,9199495749,dollworthy.dof@gmail.com,8/13/2022 11:00,NaN,NaN,...,Community Day/Back-to-School Event,NaN,1410 Englewood Ave,This event will be open to the public as well ...,100,Ebony,A Kiss Cares Inc,Social or Community Group,2603:6080:6503:5818:4802:aa00:40dd:4c69,https://www.durhamnc.gov/FormCenter/Fire-Depar...
443,23562.0,10/18/2016 16:12,Faith Academy,NaN,Priester,9198245728,Shakeemahoward@yahoo.com,11/18/2016 9:00,NaN,Durham,...,NaN,NaN,3118 Forrestal Drive,NaN,10,Shakeema,NaN,NaN,107.77.233.68,https://durhamnc.gov/FormCenter/Fire-Departmen...
684,34301.0,8/21/2017 10:49,Homewood Suites,NaN,Quesada,9194010610,yani.quesada@hilton.com,9/19/2017 13:00,NaN,Durham,...,NaN,NaN,3600 Mount Moriah,NaN,24,Yanina,NaN,NaN,70.61.92.170,http://durhamnc.gov/FormCenter/Fire-Department...
525,29792.0,3/9/2017 8:18,EK Powe Elementary School,NaN,Daye,9195619615,therese.wells@dpsnc.net,4/7/2017 9:30,NaN,Durham,...,NaN,NaN,913 Ninth Street,NaN,4 grade levels and their teachers on a rotation,Therese,NaN,NaN,152.26.176.24,http://nc-durham.civicplus.com/FormCenter/Fire...
1374,51077.0,7/2/2019 15:38,NaN,NaN,Mah,919 452 2201,kmah04@gmail.com,7/4/2019 16:00,NaN,NaN,...,4th of July Celebration,NaN,5400 Alexandra Woods Lane,4th of July Celebration with people of all age...,~120,Kim,NaN,NaN,68.73.114.6,https://durhamnc.gov/FormCenter/Fire-Departmen...
1789,67427.0,4/8/2021 12:26,NaN,NaN,Volponi,9193237819,durhamcommunitypreschool@gmail.com,4/28/2021 10:00,NaN,NaN,...,Fire Truck visit for Career Week,NaN,908 Leon Street,We are an all outdoor preschool this year and ...,25,Rose,Durham Community Preschool,School,98.26.35.99,https://durhamnc.gov/FormCenter/Fire-Departmen...
1706,57284.0,8/21/2020 13:53,NaN,NaN,Davis,919-638-5614,vandavis@nccu.edu,9/5/2020 12:30,NaN,NaN,...,Parade for Hillside Class of 70,NaN,401 E. Lakewood,3727 Fayetteville Rd is end point (Hillside Hi...,25 cars,Vanda,Reunion Committee,School,74.219.16.122,https://durhamnc.gov/FormCenter/Fire-Departmen...
898,45372.0,4/18/2018 15:25,NaN,NaN,Robinson-QA/QI Assistant,9194935013,mrobinson@sunriseclinical.org,4/27/2018 10:00,NaN,NaN,...,Fire Safety and Fire Extinguisher Training,NaN,"Sunrise Clinical Associates, PLLC 3500 Westgat...",In preparation for and in accordance with CARF...,20-30,Monica,"Sunrise Clinical Associates, PLLC",Business,45.37.102.230,https://durhamnc.gov/FormCenter/Fire-Departmen...
897,45369.0,4/18/2018 13:27,NaN,NaN,Overby,9197480849,toverby@geepglobal.com,5/16/2018 13:30,NaN,NaN,...,Annual Fire Extinguisher Training,NaN,GEEP - 2710 Weck Drive,Annual Fire Extinguisher Training,60,Tonita,GEEP USA,Business,173.226.69.50,https://durhamnc.gov/FormCenter/Fire-Departmen...
601,32834.0,5/30/2017 9:16,Durham Housing Authority,NaN,Scott,919-697-7063,rscott@dha-nc.org,6/9/2017 11:00,NaN,Durham,...,NaN,NaN,807 S. Duke St.,NaN,NaN,Robert,NaN,NaN,216.224.132.218,http://durhamnc.gov/FormCenter/Fire-Department...
1995,79783.0,3/22/2022 17:31,NaN,NaN,Sharma,8052595045,deepali2310@gmail.com,4/21/2022 17:30,NaN,NaN,...,Pack 451 cub scouts educational tour,NaN,139 East Morgan street,"Hello Firefighters, we are pack 451 cub scout ...",20,Deepali,Cub scouts pack 451 chartered with Westminster...,Social or Community Group,71.142.125.109,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1403,51506.0,7/31/2019 15:08,NaN,NaN,Dry,919-544-2000,sdry@americanrepartners.com,9/25/2019 13:00,NaN,NaN,...,Fire Extinguisher Training,NaN,430 Davis Drive,We have a four story building at this location...,50,Stacey,American Real Estate Partners,Business,66.162.13.74,https://durhamnc.gov/FormCenter/Fire-Departmen...
2758,306294.0,5/3/2024 11:14,NaN,NaN,Deatherage,9194523383,jessica.deatherage@durhamnc.gov,7/3/2024 10:00,NaN,NaN,...,DPR Summer Camp Camporee,NaN,701 Stadium Drive,Summer Camp all-site event! We are hosting a b...,100,Jessica,Durham Parks & Recreation,Government,66.192.172.42,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3088,338413.0,3/10/2025 20:27,NaN,NaN,Rigby,9194143366,Trigby@cressetchristian.org,4/19/2025 14:00,NaN,NaN,...,Easter Carnival,NaN,3707 Garrett Road,We are hosting a free community event to provi...,300,Taylor,Lifespring Church,Church,174.238.99.31,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3530,380298.0,4/1/2026 9:35,NaN,NaN,Chapman,7576422382,bande070397@att.net,4/23/2026 20:00,NaN,NaN,...,Bethesda Ruitan club meeting,NaN,1714 S Miami Blvd Durham,"I’m the VP of a civic club in Durham, the Beth...",40,Brandon 45,Bethesda Ruritan,Social or Community Group,137.201.229.44,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1500,52303.0,9/25/2019 11:15,NaN,NaN,Steele,9195362663,Onlinespeechclass123@gmail.com,10/25/2019 10:45,NaN,NaN,...,Wee Wisdom Free Prevention Week,NaN,1125 Drew Street,Free prevention week with toddlers/preschoolers,15,Debra,Wee Wisdom Preschool,School,107.15.252.68,https://durhamnc.gov/FormCenter/Fire-Departmen...
2800,313078.0,7/1/2024 12:33,NaN,NaN,Galdamez,9195969331,galdamezsoraya@gmail.com,10/4/2024 10:00,NaN,NaN,...,Daycare- Touch-A-truck Event Day,NaN,450 Muldee St.,Fireman will teach our kids in the playground ...,54,Soraya,Fellowship Baptist Church,School,45.37.164.46,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3262,355880.0,8/17/2025 17:24,NaN,NaN,Bradford,9198244146,W249safe@costco.com,9/15/2025 15:00,NaN,NaN,...,Safety Week,NaN,1510 North Pointe Dr,I would like to do a hands on fire extinguishe...,15,April,Costco,Business,174.210.70.134,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2729,302333.0,3/25/2024 15:09,NaN,NaN,Negroni,9844394634,Giancarlo.Negroni@durhamnc.gov,7/2/2024 13:30,NaN,NaN,...,Summer Camp - Durham Parks & Recreation,NaN,2000S Alston Ave,Hi! We would be honored to have the fire depar...,30,Giancarlo,Durham Parks & Recreation,Government,70.61.92.170,https://www.durhamnc.gov/FormCenter/Fire-Depar...
850,43387.0,3/7/2018 9:09,NaN,NaN,Fowler,919-687-6535,cafowler@durhambulls.com,05/08/2018 8:45 AM to 05/08/2018,NaN,NaN,...,Education Day #2 at Durham Bulls,NaN,512 S. Mangum Street,Education Day at the DBAP. We put on activity ...,"5,000",Cassie,Durham Bulls,Business,50.55.175.145,http://nc-durham.civicplus.com/FormCenter/Fire...
700,34523.0,9/11/2017 21:15,NaN,NaN,Oldham,9195481416,aoldham@myhsa.net,9/26/2017 11:00,NaN,NaN,...,Healthy Start Academy Autumn Fest,3:00 PM,807 W Chapel Hill St,"Fall festival with food, games, crafts, etc., ...",250,Autumn,Healthy Start Academy,School,71.51.252.122,https://durhamnc.gov/FormCenter/Fire-Departmen...
3105,340026.0,3/27/2025 10:19,NaN,NaN,lake,9192352673,blake@firstenvironments.org,6/4/2025 10:00,NaN,NaN,...,School Wide Visit/ Safety week,NaN,109 TW Alexander Drive,Children will be divided into 3 or 4 groups de...,135,elizabeth,First Environments Early Learning Center,School,173.42.41.194,https://www.durhamnc.gov/formcenter/fire-depar...
1377,51111.0,7/5/2019 13:37,NaN,NaN,McDonald,919-599-3370,cheryl.mcdonald@durhamnc.gov,8/6/2019 6:30,NaN,NaN,...,National Night Out at Edgemont Elm Community,NaN,Angier/Elm Street near playground,National Night Out\r\nCommunity Block Party wi...,300,Cheryl,"City of Durham, NIS",Government,66.195.223.214,https://durhamnc.gov/FormCenter/Fire-Departmen...
1808,69821.0,6/1/2021 12:40,NaN,NaN,Smith,910 520 9981,lloyd.smith@alcaminow.com,6/10/2021 10:00,NaN,NaN,...,Alcami Fire Extinguisher Training,NaN,627 Davis Drive,Fire Extinguisher training for employees at Al...,15,Lloyd,Alcami,Business,66.195.223.214,https://durhamnc.gov/FormCenter/Fire-Departmen...
184,10774.0,3/8/2016 11:44,Holton Career & Resource Center,NaN,Haire,(910) 568-7899 cell,steven.haire@dpsnc.net,4/21/2016 0:00,NaN,Durham,...,NaN,NaN,401 North Driver Street (Holton Career & Resou...,NaN,10,Steven,NaN,NaN,152.26.176.33,http://durhamnc.gov/FormCenter/Fire-Department...
2018,80454.0,4/14/2022 10:11,NaN,NaN,Locklear,2523950999,kadija.locklear@biomason.com,5/3/2022 15:00,NaN,NaN,...,Fire Extinguisher Training,NaN,12 TW Drive Durham NC,Fire Extinguisher Training for Employees,30,Kadija,Biomason,Business,174.108.252.122,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3045,334706.0,1/29/2025 20:53,NaN,NaN,Cuthrell,9196985562,megan.cuthrell@gmail.com,4/26/2025 11:00,NaN,NaN,...,Excelsior Classical Academy Spring Fling,NaN,4100 N Roxboro St,Excelsior Classical Academy K-12 public charte...,300,Megan,Excelsior parent teacher student organization,School,98.27.19.134,https://www.durhamnc.gov/FormCenter/Fire-Depar...
484,28049.0,1/31/2017 13:14,Another Coley Event/Spectacular Magazine,NaN,Coley,919-680-0465/919-697-0328,pcoley@spectacularmag.com,2/4/2017 11:45,NaN,Durham,...,NaN,NaN,Fayetteville Street @ Cornwallis,NaN,1000,Phyllis,NaN,NaN,50.55.174.125,http://durhamnc.gov/FormCenter/Fire-Department...
2872,319825.0,8/26/2024 12:21,NaN,NaN,Wriedt,919-354-6173,gspkoffice@gmail.com,10/10/2024 9:30,NaN,NaN,...,Preschool Visit,NaN,2601 Hillsborough Rd,Fire truck visit to Preschool,20,Janice,Grey Stone Preschool & Kindergarten,School,65.190.116.198,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1998,79852.0,3/24/2022 16:25,NaN,NaN,Nienke,9192195740,jnienke@spoonflower.com,4/14/2022 14:00,NaN,NaN,...,Fire Extinguisher training,NaN,3871 S Alston Ave,Training for maintenance department to learn a...,8 to 9,Jack,Fire Department,Business,98.101.190.234,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3034,333117.0,1/13/2025 12:38,NaN,NaN,Wrightson,8433015527,joy.wrightson@gmail.com,7/4/2025 9:00,NaN,NaN,...,July 4th Parade,NaN,300 Nichols Farm Dr Grove Park,Annual July 4th parade,75-80,Joy,USSA,Social or Community Group,50.55.170.134,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1279,49715.0,4/1/2019 13:08,NaN,NaN,Marlowe,9192260043,tara@southpointpets.com,5/29/2019 12:00,NaN,NaN,...,Employee Training,NaN,5601 Fayetteville Road,Would like to do a fire extinguisher training ...,30,Tara,Southpoint Animal Hospital,Business,108.169.154.114,https://durhamnc.gov/FormCenter/Fire-Departmen...
1245,49380.0,3/6/2019 11:39,NaN,NaN,Jefferies,919-560-2000 ext 64231,tabitha.jefferies@dpsnc.net,4/17/2019 10:00,NaN,NaN,...,Pearsontown Elementary School Career Day,NaN,4915 Barbee Rd.,Career Day for all students. Pre-K- 2nd grades...,360 students,Tabitha,Pearsontown,Social or Community Group,152.26.176.40,https://durhamnc.gov/FormCenter/Fire-Departmen...
1541,52540.0,10/10/2019 15:53,NaN,NaN,Ortiz,252-886-3837,ortizceo84@yahoo.com,10/23/2019 9:30,NaN,NaN,...,Calvary Church Preschool,NaN,1204 Lynn Road Durham NC,"Fire Prevention with the school, the students ...",60,Carlos,Calvary Church,School,174.109.109.61,https://durhamnc.gov/FormCenter/Fire-Departmen...
2783,308972.0,5/29/2024 9:28,NaN,NaN,Brothers,9199739413,alexander_brothers@dpsnc.net,9/11/2024 17:00,NaN,NaN,...,Eno Valley Community Health and Safety Night,NaN,"117 Milton Road, Durham NC",A community event for the students and familie...,200,Alexander,Durham Public Schools,School,152.22.48.24,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2649,296054.0,1/9/2024 10:26,NaN,NaN,Nannery,781-752-6724,Nannerymicaela@gmail.com,2/5/2024 11:30,NaN,NaN,...,Do y’all help replace smoke alarm batteries th...,NaN,363 Red Elm Dr,Need help replacing a very high smoke alarm’s ...,1,Micaela,NaN,Social or Community Group,75.58.60.26,https://www.durhamnc.gov/FormCenter/Fire-Depar...
673,34089.0,8/8/2017 9:44,"Supreme Youth Development Center, Inc",NaN,Broady,919-824-0891,kbroady2011@gmail.com,9/9/2017 13:30,NaN,Durham,...,NaN,NaN,1217 Hearthside St.,NaN,50,Kelly,NaN,NaN,172.58.152.203,https://durhamnc.gov/FormCenter/Fire-Departmen...
2079,82945.0,7/1/2022 10:43,NaN,NaN,Super,919-560-4935 ext. 29484,Nicole.Super@durhamnc.gov,8/10/2022 11:00,NaN,NaN,...,Back to School Event,NaN,1155 Briar Rose Ln,This will be a Back to School Event that will ...,80,Nicole,Durham Police Department,Business,74.219.16.122,https://www.durhamnc.gov/FormCenter/Fire-Depar...
321,18479.0,7/14/2016 10:10,Orange Grove Missionary Batpist Church,NaN,Overton,9198627033,kavanoverton@yahoo.com,8/13/2016 10:30,NaN,Durham,...,NaN,NaN,505 East End Ave,NaN,100-200,Kavan,NaN,NaN,70.60.99.26,https://durhamnc.gov/FormCenter/Fire-Departmen...
2211,86387.0,10/6/2022 12:08,NaN,NaN,Volponi,9193237819,durhamcommunitypreschool@gmail.com,10/19/2022 9:00,NaN,NaN,...,Fire Truck visit to preschool,NaN,908 Leon Street,We would love to have a fire truck and fire fi...,37,Rose,Durham Community Preschool,School,98.26.35.99,https://www.durhamnc.gov/FormCenter/Fire-Depar...
65,1727.0,9/29/2015 23:00,FAYETTEVILLE STREET ELEMENTARY SCHOOL,NaN,HOWARD,919-560-3944,Teresa.Howard@dpsnc.net,10/13/2015 9:30 AM to 10/13/2015 11:00 AM,NaN,DURHAM,...,NaN,NaN,2905 FAYETTEVILLE STREET,NaN,Approximately 190 students,TERESA,NaN,NaN,24.40.128.216,http://durhamnc.gov/FormCenter/Fire-Department...
168,9860.0,2/22/2016 11:20,EK Powe Elementary,NaN,Walton,919-475-3349,laura.walton@dpsnc.net,3/24/2016 10:00,NaN,Durham,...,NaN,NaN,913 9th St,NaN,540,Laura,NaN,NaN,152.26.176.40,http://durhamnc.gov/FormCenter/Fire-Department...
931,45865.0,5/23/2018 13:20,NaN,NaN,Simpson,9196234994,robynleesimp@aol.com,6/23/2018 10:00,NaN,NaN,...,Bethel Family Worship Center Community Fami...,NaN,"515 Dowd Street Durham, NC",Annual Community Event. This is a day for the ...,100-200,Robyn,Bethel Family Worship Center,Church,71.142.5.104,http://durhamnc.gov/FormCenter/Fire-Department...
1648,54330.0,3/2/2020 14:01,NaN,NaN,Newton,9196492241,ksbrock4@gmail.com,4/7/2020 9:00,NaN,NaN,...,Oak Grove Career Fair,NaN,3810 Wake Forest HWY Durham NC,Career Day from 9-11,300,Karmen,Oak Grove Elementary School,School,198.85.255.10,https://durhamnc.gov/FormCenter/Fire-Departmen...
686,34305.0,8/21/2017 13:34,Aldersgate Weekday Preschool,NaN,Golden,919-479-8686,tammy@aldersgate.org,10/24/2017 10:30,NaN,Durham,...,NaN,NaN,1320 Umstead Rd,NaN,30 two year olds,Tammy,NaN,NaN,98.101.162.126,http://durhamnc.gov/FormCenter/Fire-Department...
315,18077.0,7/7/2016 13:42,National Night Out,NaN,Davis,9199244347,Apexrobin@aol.com,8/2/2016 18:00,NaN,Durham,...,NaN,NaN,1101 Spruce street,NaN,35,Robin,NaN,NaN,107.15.255.230,https://durhamnc.gov/FormCenter/Fire-Departmen...
2781,308833.0,5/28/2024 11:57,NaN,NaN,Wise,919-560-0236,lwise@dconc.gov,7/27/2024 10:00,NaN,NaN,...,Summer Reading Finale,NaN,221 Milton Road,An hour-long finale to conclude our Summer Rea...,100?,Lauren,Durham County Library - North Regional Library,Government,168.215.136.111,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2493,110546.0,8/24/2023 10:08,NaN,NaN,Kahl,7032204392,mkahl44@gmail.com,10/28/2023 16:30,NaN,NaN,...,Marydell Neighborhood Annual Fall BBQ Gathering,NaN,"4111 Amesbury Lane, Durham, NC",Neighborhood BBQ that brings together the adul...,25 kids,Michael,Marydell Neighborhood HOA,Social or Community Group,99.150.230.52,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1092,47525.0,9/24/2018 18:35,NaN,NaN,Wiener,9194524838,ehwiener21@gmail.com,10/31/2018 16:30,NaN,NaN,...,Hope Valley Neighborhood Assoc Halloween Parade,NaN,Somerst at Westover,We would love for the Fire Department to come ...,200,Elisabeth,Hope Valley Neighborhood Association,Social or Community Group,50.111.91.110,http://durhamnc.gov/FormCenter/Fire-Department...

In [488]:
print(df.columns.tolist())

['ID', 'Submission Date', 'Organization Name', 'Your First Name', 'Last Name', 'Phone Number', 'Email Address', 'Desired Date & Time of Event', 'Address of Event', 'City', 'State', 'Zip Code', 'Total Number of Children, Adults or both Participating in the Event', 'Fire Safety/Fire Prevention Programs', 'Additional Request or Questions?', 'Available Sations for Tour', 'Fire Safety/Fire Prevention Programs.1', 'Available Stations for Tour', 'Name of Event', 'End Time of the Event', 'Street Address of Event', 'Event Description', 'Anticipated Number of Participants', 'First Name', 'Agency Name', 'Type of Agency', 'IP Address', 'Referrer']

#### Data Cleaning

In [489]:
# Ensuring datetime type
df["Submission Date"] = pd.to_datetime(df["Submission Date"])

# Splitting into separate columns
df["Date of Submission"] = df["Submission Date"].dt.date.astype(str)   # YYYY-MM-DD
df["Time of Submission"] = df["Submission Date"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Submission Date"])

# Moving new columns to the front
cols = ["Date of Submission", "Time of Submission"] + [c for c in df.columns if c not in ["Date of Submission", "Time of Submission"]]
df = df[cols]

In [490]:
# Dropping unnecessary columns
df = df.drop(columns=["ID", "Your First Name", "Last Name", "Phone Number",
                     "Desired Date & Time of Event", "Address of Event", "City", "State", "Zip Code", 
                      "Total Number of Children, Adults or both Participating in the Event",
                     "Fire Safety/Fire Prevention Programs", "Additional Request or Questions?", 
                     "Available Sations for Tour", "Fire Safety/Fire Prevention Programs.1", "Available Stations for Tour", 
                     "End Time of the Event", "First Name", "IP Address", "Referrer", 
                      "Street Address of Event", "Organization Name", "Agency Name", "Type of Agency"])
display(df.sample(5))
print(df.columns.tolist())

,Date of Submission,Time of Submission,Email Address,Name of Event,Event Description,Anticipated Number of Participants
2927,2024-09-20,11:41:00,yoki@visitimmanuel.org,Fall Festival and Chili Cook-Off,We are holding a fall festival that is open to...,150-200
2404,2023-05-23,16:18:00,Cjjonesjr21@yhoo.com,Community Celebration,"We are having a community fun day with food, g...",150
242,2016-05-12,12:33:00,ssoutherland@geepglobal.com,NaN,NaN,53
3554,2026-04-27,19:48:00,darlene.brannon525@gmail.com,Safety Week,Age 4 years old to 11 years old\r\nI want chil...,30
2710,2024-03-11,12:29:00,ashley_lee@stores.gap.com,Kids safety event,"On Sat., 5/11, Old Navy stores will host the o...",100

['Date of Submission', 'Time of Submission', 'Email Address', 'Name of Event', 'Event Description', 'Anticipated Number of Participants']

In [491]:
# Converting to datetime safely
df["Date of Submission"] = pd.to_datetime(df["Date of Submission"], errors="coerce")

# Filtering only 2025 and 2026 rows (BEFORE any other operations)
df = df[df["Date of Submission"].dt.year.isin([2025, 2026])].copy()

# Sorting by date in descending order
df = df.sort_values("Date of Submission", ascending=False)


word_map = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4,
    "five": 5, "six": 6, "seven": 7, "eight": 8, "nine": 9,
    "ten": 10, "eleven": 11, "twelve": 12, "thirteen": 13,
    "fourteen": 14, "fifteen": 15, "sixteen": 16, "seventeen": 17,
    "eighteen": 18, "nineteen": 19, "twenty": 20,
    "thirty": 30, "forty": 40, "fifty": 50,
    "sixty": 60, "seventy": 70, "eighty": 80,
    "ninety": 90, "hundred": 100
}


def parse_word_number(text):
    t = text.strip().lower()
    return word_map.get(t, None)


def clean_participants(text):
    if pd.isna(text):
        return np.nan

    t = str(text).lower().replace(",", "").strip()

    nums = [float(x) for x in re.findall(r'\d+(?:\.\d+)?', t)]

    # Missing / invalid
    if not nums and not any(w in t for w in word_map):
        return np.nan

    # Homes excluded
    if "home" in t or "homes" in t:
        return np.nan

    # Word-only numbers (Fifty → 50)
    word_num = parse_word_number(t)
    if word_num is not None:
        return float(word_num)

    # OVER X → X
    over_pattern = re.search(r'\bover\s+(one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s*(hundred)?', t)
    if over_pattern:
        base = over_pattern.group(1)
        mult = over_pattern.group(2)

        if base.isdigit():
            value = float(base)
        else:
            value = float(word_map.get(base, np.nan))

        if mult:
            value *= 100

        return value

    # STRICT CLASS RULE (80 4 classes ...)
    strict_class_pattern = re.search(r'^\s*(\d+)\s+\d+\s*classes', t)
    if strict_class_pattern:
        return float(strict_class_pattern.group(1))

    # Room range per class
    room_class_pattern = re.search(
        r'(\d+)\s*(?:to|-)\s*(\d+)\s*(?:children|kids|students).*?(\d+)\s*classes',
        t
    )

    if room_class_pattern:
        low = float(room_class_pattern.group(1))
        high = float(room_class_pattern.group(2))
        classes = float(room_class_pattern.group(3))

        return ((low + high) / 2) * classes

    # Explicit total
    total = re.search(r'(\d+)\s*total', t)
    if total:
        return float(total.group(1))

    # Classroom inference
    classroom_pattern = re.search(r'\d+\s*(classrooms|classes).*?(?:so|about).*?(\d+)', t)
    if classroom_pattern:
        return float(classroom_pattern.group(2))

    # Group ranges
    group_pattern = re.search(r'(\d+)\s*(groups|classes|sessions).*?(\d+)\s*(?:-|to)\s*(\d+)?', t)
    if group_pattern:
        groups = float(group_pattern.group(1))
        if group_pattern.group(4):
            low = float(group_pattern.group(3))
            high = float(group_pattern.group(4))
            return groups * ((low + high) / 2)
        return groups * float(group_pattern.group(3))

    # Slash values
    slash_pattern = re.findall(r'(\d+)\s*/\s*(\d+)', t)
    if slash_pattern:
        values = [np.mean([float(a), float(b)]) for a, b in slash_pattern]
        return np.mean(values)

    # Age grouping
    age_group_pattern = re.findall(r'(\d+)\s*(?:year|yr|yo|old)', t)
    if age_group_pattern:
        return sum(float(x) for x in age_group_pattern)

    # Role-based sums
    role_keywords = [
        "children", "kids", "adults", "students",
        "teachers", "parents", "boys", "girls"
    ]

    if any(k in t for k in role_keywords) and len(nums) > 1:
        if re.match(r'^\d+\s*-', t):
            return sum(nums[1:])
        return sum(nums)

    # Numeric ranges
    if re.search(r'\d+\s*-\s*\d+', t):
        pairs = re.findall(r'(\d+)\s*-\s*(\d+)', t)
        return np.mean([np.mean([float(a), float(b)]) for a, b in pairs])

    return nums[0]


# Applying cleaning
df["Participants_Clean"] = df["Anticipated Number of Participants"].apply(clean_participants)

# Splitting into yearly dataframes
df_2025 = df[df["Date of Submission"].dt.year == 2025].copy()
df_2026 = df[df["Date of Submission"].dt.year == 2026].copy()

# Renaming columns
for d in [df_2025, df_2026]:
    d.rename(columns={
        "Date of Submission": "Submission Date",
        "Time of Submission": "Submission Time"
    }, inplace=True)

#### Displaying Nan values in Participants_Clean

In [492]:
debug_df = df[df["Participants_Clean"].isna()][
    ["Anticipated Number of Participants", "Participants_Clean"]
]

display(debug_df)

     Anticipated Number of Participants  Participants_Clean
3553                                N/a                 NaN
3429                   Approx. 25 homes                 NaN
3209                                NaN                 NaN

#### Displaying count and samples

In [493]:
# Removing NaNs after cleaning
df_2025 = df_2025.dropna(subset=["Participants_Clean"])

# Row Count
display(f"2025 rows: {len(df_2025)}")

'2025 rows: 411'

In [494]:
display(df_2025.sample(60))

,Submission Date,Submission Time,Email Address,Name of Event,Event Description,Anticipated Number of Participants,Participants_Clean
3185,2025-06-02,14:38:00,miller.tom2022@gmail.com,76th Annual Watts Hospital-Hillandale Neighbor...,This a short parade around two blocks in the W...,300-500,400.0
3087,2025-03-10,14:54:00,jamo@gsdurham.com,Easter Eggstravaganza,Easter Egg Hunt with games/activities for fami...,600,600.0
3234,2025-07-24,13:52:00,jfoster@hemosonics.com,Fire Extinguisher Training,Live Fire Extinguisher training for employees.,50,50.0
3053,2025-02-07,08:18:00,Special.Washintgon@Kindercare.com,School-Age field trip,Bring our School-age group to do a fire statio...,25,25.0
3167,2025-05-16,10:01:00,bria@bookharvest.org,Book Harvest's Summer Block Party,Book Harvest’s beloved Summer Block Party prom...,"1,000+",1000.0
3383,2025-10-09,17:07:00,ehwiener21@gmail.com,Hope Valley Neighborhood Association Halloween...,The Hope Valley Neighborhood Association spons...,200+,200.0
3312,2025-09-08,21:43:00,willeden4@gmail.com,Grant's 5th Birthday,Our son is turning 5 and could not be more exc...,4,4.0
3376,2025-10-07,15:13:00,jon.espitia@gmail.com,Southwest Elementary Community Workers Day,The 1st graders of Southwest Elementary are le...,40,40.0
3107,2025-03-28,11:33:00,hdavispark@hrpliving.com,Touch-A-Truck Event,We have 287 apartment units and lots of childr...,70,70.0
3164,2025-05-13,00:10:00,NaN,Amazing Camp Adventure: Shaping Future STEAM E...,Located at the Ivy Center in Durham our event ...,30,30.0
3287,2025-08-29,12:25:00,kyrasplace9@gmail.com,"community day ,would like for the fire truck...","this event is for the church and community , t...",100,100.0
3418,2025-11-04,09:46:00,debhartmom@msn.com,Community Helpers,Our preschool is having community helpers week...,60,60.0
3040,2025-01-21,16:37:00,kyrasplace9@gmail.com,family & friends day,"this event is for the church & community, it w...",150,150.0
3281,2025-08-27,13:57:00,mkahl44@gmail.com,Marydell Neighborhood Annual Fall BBQ Gathering,Neighborhood BBQ that brings together the adul...,25 kids,25.0
3365,2025-09-30,16:29:00,awilson@epworth-umc.org,Fall Harvest Festival,Free outdoor community festival with bounce ho...,150,150.0
3358,2025-09-29,14:33:00,40.Jparker@nhaschools.com,School Safety Week: Fire Safety Day,November 3rd through November 6th will be Scho...,500,500.0
3176,2025-05-23,09:36:00,ross@triangleultimate.org,Southeast Social,"Join us on Friday, July 18th from 6:00–7:30pm ...",100,100.0
3246,2025-08-06,18:45:00,cheresasimpson@gmail.com,National Night Out,We are requesting a visit with a vehicle for r...,150,150.0
3146,2025-05-01,17:22:00,dgomez@elfuturo-nc.org,El Futuro Mother's Day Kermes,KERMES IN THE GREEN SPACE: Mother's Day Celebr...,400,400.0
3438,2025-11-24,12:52:00,greenspace@elfuturo-nc.org,Las Posadas,"Join us on Monday, December 15th at 5:30 PM fo...",200,200.0
3079,2025-03-04,09:33:00,dellis@durhamcharter.org,Durham Charter School Career Day,We are preparing a career day for our students...,100,100.0
3038,2025-01-16,14:10:00,fhgalberth@gmail.com,Grove Park Christmas Parade,This is our annual Christmas Parade to be lead...,10,10.0
3316,2025-09-10,13:07:00,Rene.Burden1978@gmail.com,HOA Community Meet & Greet,"Yearly, the HOA board host a community meet & ...",40,40.0
3104,2025-03-27,09:25:00,nicole.velasquez@linde.com,LInde Gas & Equipment Safety Day,This is an annual event for our company. We h...,50,50.0
3385,2025-10-13,11:08:00,arios3686@gmail.com,Chancellor's Ridge Neighborhood Oktoberfest,"We had to cancel due to the rain, hope you can...",300,300.0
3047,2025-01-31,10:38:00,frances_williams@dpsnc.net,Spring Valley Career Day,Career Day for Elementary Students,100,100.0
3183,2025-05-29,14:52:00,jennifer@littlestepsbigleapsaba.com,Touch a Truck Event,Would love to schedule a touch a truck event f...,5,5.0
3062,2025-02-13,18:59:00,takileak@gmail.com,Safety procedure and career training support a...,Hello my name is Taki Jamel Leak Bell and I wa...,1150,1150.0
3060,2025-02-13,14:21:00,Iburgos@fcrinc.org,Daycare or Classroom visit,Learning about community helpers and how they ...,11,11.0
3208,2025-06-27,10:36:00,annie.quarcoopome@gmail.com,Fire station tour,A visit to the fire station with a 5 year old,3,3.0
3142,2025-04-29,09:18:00,40.jpeterson@nhaschools.com,RTCA Career Day,We will have a career day for our K-8 grade 8:...,754,754.0
3071,2025-02-24,12:45:00,Special.Washintgon@Kindercare.com,KinderCare Learning Center,Staying Safe,50,50.0
3364,2025-09-30,13:11:00,aurelia@fpdayschool.org,Fire Station Tour or Fire Safety House For Sch...,Local preschool near the fire station would li...,25,25.0
3061,2025-02-13,15:09:00,peggy.leach@hilton.com,Employee Fire Safety training,Train employees on how to use a fire extinguis...,25,25.0
3247,2025-08-08,11:03:00,aclove58@gmail.com,The Funeral Is Cancelled,The Funeral Is Cancelled. Pertaining to Gun V...,300,300.0
3220,2025-07-16,13:16:00,dlyons@fcrinc.org,Pre-Service Training,Teachers need annual training on how to use th...,85+/-,85.0
3373,2025-10-07,11:42:00,NaN,Fire Prevention/ Crime Prevention,"Come talk to the children about fire safety, t...",30,30.0
3422,2025-11-05,09:10:00,shannon.duke@duke.edu,Career Day,"Pre K, Kindergarten, First Grade students",40+,40.0
3255,2025-08-13,14:48:00,youthministry@mvbcdurham.org,Hallow Be Thy Ween Block Party,Halloween alternative block party.,60,60.0
3175,2025-05-20,16:03:00,superahav@gmail.com,Touch-A-Truck Event - Birthday party,"Birthday party for four year old son, party th...",15,15.0
3078,2025-03-03,10:38:00,teshaking09@gmail.com,Voyager Academy Spring Fling,This is one of our largest events on campus. T...,2500+,2500.0
3404,2025-10-27,14:28:00,carolineh@kingspark.org,Family Fun Night,"Join us for Family Fun Night! On Friday, Octob...",500,500.0
3284,2025-08-27,20:18:00,Deedawson1@gmail.com,AMC Family Resource Center Community Event,We are giving back to the community this day b...,200,200.0
3356,2025-09-29,11:17:00,kinchildcareprogram@gmail.com,"KIN, too Child Care Program",Young children to have the experience of the f...,13,13.0
3256,2025-08-14,09:11:00,myw@artfulgreetings.com,Pre-K Fire Truck Visit,Brief talk in the Pre-k classroom about fire s...,50,50.0
3227,2025-07-18,09:56:00,astorey@carolinaflow.com,CORRECTED DATE- Fire Drill- CCG Business Site-...,Observation of fire drill for second site. The...,60,60.0
3318,2025-09-12,09:41:00,khendereson@lightbridgeacademy.com,Fire Prevention week,We would like for the fire fighters to come an...,50,50.0
3414,2025-11-01,13:21:00,taronya_smith@yahoo.com,Taronya Smith,School visit,120,120.0
3442,2025-12-10,10:31:00,whisenant@mcadamsco.com,Fire Drill Observation,Fire Drill,30-45,37.5
3192,2025-06-11,16:35:00,Trevor.scalercio@hines.com,Hock Plaza Fire Drill,Building-wide fire drill,400,400.0
3407,2025-10-28,14:53:00,tom.griffith92@gmail.com,Cub Scout Pack 486,Cub scout pack to tour local fire station,25,25.0
3149,2025-05-05,12:53:00,Rfairleylcv@gmail.com,We Are Kings & We are Queens,Last mentoring session of the year with the st...,20,20.0
3182,2025-05-29,11:00:00,ramon.grillasca@durhamnc.gov,Durham Police Department Summer Camp,Middle school aged children taking a tour of t...,15 children 5 adults,20.0
3288,2025-08-29,15:43:00,alex.kaplan@durhamnc.gov,Welcome Back to After School,Welcome back to after school parent event. We ...,20,20.0
3372,2025-10-06,12:58:00,Dkfoust43@gmail.com,Lowes Fire Safety Event,Fire safety event to drive fire safely for our...,50,50.0
3270,2025-08-20,14:35:00,Torrey.swain@gmail.com,Cardinal Lake NNO Event,Our community’s annual NNO Event,200-300,250.0
3269,2025-08-19,17:57:00,asgoetz@hotmail.com,National Night Out,NNO event,100,100.0
3158,2025-05-09,13:24:00,bweber@measinc.com,Durham Central Park Children's Parade,The Durham Central Park July 4th Children's pa...,800,800.0
3273,2025-08-22,11:43:00,pacarter52@gmail.com,National night out,National night out,150,150.0
3351,2025-09-25,13:52:00,kkcdcteachers@gmail.com,Fire Prevention Day,Our kids aged 2-5 will come out and see the fi...,20,20.0

In [495]:
# Removing NaNs after cleaning
df_2026 = df_2026.dropna(subset=["Participants_Clean"])

# Row Count
display(f"2026 rows: {len(df_2026)}")

'2026 rows: 130'

In [496]:
display(df_2026.sample(60))

,Submission Date,Submission Time,Email Address,Name of Event,Event Description,Anticipated Number of Participants,Participants_Clean
3477,2026-02-13,10:54:00,kathy_conner@dpsnc.net,CC Spaulding Elementary School Career Day,Career Day: Kindergarten and 1st Grade Studen...,3 groups of 35-45 students each,120.0
3548,2026-04-21,16:57:00,Fernanda@durhamleap.org,Classroom Visit,Preschool kids 3-5 years old will be learning ...,50,50.0
3462,2026-01-27,09:08:00,elizabeth_reinstein@dpsnc.net,Spring Fling,I’m helping organize Oak Grove Elementary Scho...,200,200.0
3556,2026-04-28,19:44:00,dcooper2@nhaschools.com,Career Day,We are excited to host our upcoming Career Fai...,88,88.0
3516,2026-03-19,14:34:00,Jaydnmcneil8@gmail.com,Community Day,A day of fellowship for our community,200,200.0
3487,2026-02-26,12:38:00,eva@communityhealthcoalition.com,Community Health Festival,The Community Health Fair is a collaborative o...,1000,1000.0
3571,2026-05-13,15:00:00,vparrish1221@gmail.com,Summer Literacy Initiative,I am the Enrichment Coordinator for the Summer...,12,12.0
3489,2026-03-02,10:39:00,bryson_byrd@dpsnc.net,Primary Class Visits,Pre-K and Kindergarten Students will get to se...,144,144.0
3567,2026-05-08,10:11:00,michelle_seabrook@dpsnc.net,First Grade Celebration,First Grade is having a celebration for all th...,80,80.0
3521,2026-03-23,18:40:00,tomikasmall@gmail.com,Youth Explosion and Juneteenth Celebration,This annual event is an outreach fellowship fo...,100,100.0
3552,2026-04-27,11:30:00,tomya.williams@lapetite.com,Daycare visit,Daycare visit for entire school,70,70.0
3485,2026-02-25,17:00:00,DiMaria.rebecca@gmail.com,2nd annual Fhna Spring Fling,Pull into the parking lot by the tennis courts...,50,50.0
3568,2026-05-11,16:09:00,mkahl44@gmail.com,Marydell Neighborhood Annual Fall BBQ Gathering,Neighborhood BBQ that brings together the adul...,25 kids,25.0
3524,2026-03-24,17:07:00,candourhouse@greystar.com,Fire Safety Day,We would like to host a Fire Safety Event for ...,60-80 people,70.0
3576,2026-05-15,15:13:00,brooke.yingling@durhamnc.gov,Walltown Summer Camp,Durham Parks & Rec Summer Camp,30,30.0
3566,2026-05-07,14:38:00,collinf@hopenorthcarolina.org,North Street Neighborhood Fire Station Tour,I would like to bring a small group of adults ...,12,12.0
3546,2026-04-21,10:26:00,deborah.pemberton@duke.edu,FPDC Safety Week-Fire Extinguisher Training,Our department (Duke Facilities Planning Desig...,40-50,45.0
3562,2026-05-04,09:35:00,emma@realityministries.org,Fire Station Tour,This event will be for Reality Ministries and ...,15,15.0
3534,2026-04-06,20:46:00,Tkpenn@aol.com,Cub Scout Pack 405 Tour,We’d love to tour Station 15. Our Cub Scouts r...,"13 boys, 13 parents",26.0
3453,2026-01-13,12:01:00,belinda@msdurham.org,Fire Extinguisher Training for Staff and Eleme...,Montessori School of Durham - fire extinguishe...,50,50.0
3565,2026-05-06,13:03:00,mshunicutt@aol.com,Crystal Lake Fire Prevention & Safety Seminar,To educate and raise awareness of proper fire ...,50 - 75,62.5
3511,2026-03-16,14:48:00,kennedy@kestrelheights.org,Kestrel Heights Career Day,"We will be hosting a Career Day on Friday, Mar...",84,84.0
3476,2026-02-12,23:14:00,vicepresident2@namidurham.org,"ALLIANCE HEALTH PRESENTS NAMI DURHAM MIND, BOD...","The NAMI Durham Mind, Body & Soul Wellness Exp...",200,200.0
3507,2026-03-11,12:36:00,kisha.dixon@kindercare.com,Staying Safe,"Our center will be talking about Staying Safe,...",42,42.0
3513,2026-03-18,01:18:00,hgsansone1956@gmail.com,Woodlake Independence Day parade,About 1/2 mile parade with adults and kids and...,100,100.0
3538,2026-04-11,12:42:00,perry1angel@gmail.com,FCCI Health and Business Expo,Health information \r\nLine dance\r\nSmall bus...,15 - 20,17.5
3480,2026-02-19,18:07:00,mdevika@unc.edu,Fire Safety Workshop for Youth in Special Educ...,"My name is Devika, and I am a senior at UNC Ch...",27,27.0
3577,2026-05-15,15:16:00,ahmir.davenport@durhamnc.gov,Touch a Truck Event,Durham Parks & Recreation Summer Camp,30,30.0
3506,2026-03-10,12:29:00,Teresa_Hayes@dpsnc.net,Fire Extinguisher Training for FF I Students,My FF I students will need to be checked off f...,16 (1st round) 12 (2nd round),16.0
3564,2026-05-04,18:52:00,tonya.williams3@lapetite.com,Daycare visit,Having the children to come to see the truck. ...,55,55.0
3527,2026-03-29,13:06:00,megand.huggins@gmail.com,Daycare Visit,We would like to educate the children and allo...,150,150.0
3526,2026-03-26,13:40:00,khenderson@lightbridgeacademy.com,touch a truck,We would like for our children to touch a truc...,80,80.0
3493,2026-03-05,09:25:00,ceconomou@dconc.gov,Durham Main Library's Summer Reading Kickoff,Every Summer we have a kickoff to our Summer R...,400,400.0
3509,2026-03-15,12:51:00,Tachris@gap.com,Old Navy Safety Day,Every year Old Navy hosts a safety event and w...,50-100,75.0
3482,2026-02-22,15:56:00,mitchellbrittney@outlook.com,Community Helpers Week,One of our preschool classes is learning about...,"The preschool class has 18 children, but we’d ...",18.0
3518,2026-03-20,16:14:00,Trigby@cressetchristian.org,Family Easter fun day,Church community outreach Easter carnival fun day,400-500,450.0
3573,2026-05-14,16:05:00,brenda.jones@ratpdev.com,CPR Hands Only,GoDurham requesting Hands-On Only CPR Training...,15 - 20,17.5
3468,2026-02-04,08:32:00,michelle_parks@dpsnc.net,R.N. Harris Elementary school,We are having a career fair at our school on A...,150,150.0
3581,2026-05-16,12:45:00,Capricia_Johnsonammo@dpsnc.net,Fire Truck : Spring Valley Career Day Event: B...,Kindergarten Students are learning about Fire ...,88,88.0
3557,2026-04-29,14:51:00,lindsey@hvcc.org,Summer Camp,We would like to do a fire safety class for ou...,24,24.0
3540,2026-04-14,09:52:00,April_Henderson@dpsnc.net,Touch a Truck,For 3 pre-k classes at Murray-Massenburg Eleme...,50,50.0
3472,2026-02-09,13:29:00,special.washington@kindercare.com,Fire Station Tour,Staying Safe,28,28.0
3492,2026-03-04,13:09:00,potter@firstcalvary.org,Calvary Festival Family Fun Day-Community Day ...,Calvary Festival Family Fun Day-Community Day ...,500-1000,750.0
3537,2026-04-09,09:32:00,samantha.davey@duke.edu,"Dukes in Motion: Firefighter Day (hoses, gear,...","We will be having 20 kids, 20-25 volunteers, a...",20,20.0
3572,2026-05-14,15:58:00,brenda.jones@ratpdev.com,CPR - Hands Only,Request CPR Hands Only training for our employ...,15 - 20,17.5
3574,2026-05-14,16:07:00,brenda.jones@ratpdev.com,Hands-On Only CPR,GoDurham requesting Hands-On Only CPR Training...,15 - 20,17.5
3559,2026-04-30,21:55:00,Kreativekidznc@gmail.com,Community Helpers Week,Teaching/exposing children ages 1-5 to those w...,8,8.0
3488,2026-02-27,10:41:00,judith_faggart@dpsnc.net,George Watts Montessori School\r\nClassroom Visit,Fire Safety for Pre-K and Kindergarten,100,100.0
3525,2026-03-25,10:58:00,bria@bookharvest.org,Book Harvest's Annual Summer Block Party,The afternoon will be filled with family activ...,3000,3000.0
3543,2026-04-16,18:25:00,sstaple1@eagles.nccu.edu,Community Helpers,This event is for preschoolers. We'll be learn...,30 children,30.0
3486,2026-02-26,08:28:00,Katiehduke@gmail.com,Fire station tour,Family of 4 with 2 boys curious how firemen do...,4,4.0
3579,2026-05-15,15:22:00,lauren.michal@durhamnc.gov,Touch A Truck,Durham Parks & Recreation Summer Camp,30,30.0
3501,2026-03-07,16:22:00,nursenikkisnewsnetwork@gmail.com,ABCs of Community Readiness,Subject: Invitation to Collaborate - LGBT+ BIP...,>100,100.0
3460,2026-01-22,06:29:00,kimlt69@yahoo.com,LABOR IN LOVE,Community resources,60,60.0
3475,2026-02-12,10:46:00,nancy.holec@ymcatriangle.org,Healthy Kid Day,As we celebrate the YMCA’s 175 years of streng...,100,100.0
3484,2026-02-25,11:26:00,ebony_brim-kinte@dpsnc.net,Ignite! Culture Fest,We are having a school wide (K-12) event for t...,25 students with a few adult bystanders,25.0
3498,2026-03-06,14:17:00,Hellokitty320@gmail.com,FBLA Career Day,Future Business Leaders of America (FBLA) is h...,670 (rotating throughout the day),670.0
3561,2026-05-01,16:52:00,gintas.juzumas@duke.edu,"Fire Extinguisher Training, Carmichael Building",On 10/5/26 at 9:15 AM we have scheduled Carmic...,30,30.0
3584,2026-05-19,17:32:00,miller.tom2022@gmail.com,77th Annual Watts-Hillandale July 4 Parade and...,This a neighborhood July 4 foot parade and cel...,400,400.0
3499,2026-03-07,11:31:00,fhgalberth@gmail.com,National Night Out,National Night Out Event\r\nWould like the tea...,75,75.0