#### Importing Libraries

In [188]:
import pandas as pd
from IPython.display import display
import numpy as np
import os
import re

In [189]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Captain_Burtons/input/Akunna.csv")
display(df.sample(50))

,ID,Submission Date,Organization Name,Your First Name,Last Name,Phone Number,Email Address,Desired Date & Time of Event,Address of Event,City,...,Name of Event,End Time of the Event,Street Address of Event,Event Description,Anticipated Number of Participants,First Name,Agency Name,Type of Agency,IP Address,Referrer
720,34648,9/20/2017 8:21,NaN,NaN,Clark,919-402-1500,director@familypreschool.org,10/25/2017 10:45,NaN,NaN,...,Firetruck Visit to Family Preschool,11:30 AM,4907 Garrett Road,Firetruck to visit our preschool where childre...,35,Emily,Family Preschool,School,107.15.40.251,http://durhamnc.gov/FormCenter/Fire-Department...
140,8191,1/21/2016 11:52,Montessori Community School,NaN,Wilson,919-264-7395,NaN,1/27/2016 5:15,NaN,Durham,...,NaN,NaN,Montessori Community School 4512 Pope Road,NaN,50,Linda,NaN,NaN,98.26.58.166,http://durhamnc.gov/FormCenter/Fire-Department...
2369,97369,4/7/2023 16:47,NaN,NaN,Abadia,610-724-0602,jmabadia@verizon.net,5/29/2023 8:45,NaN,NaN,...,Memorial Day Observation at Carolina Arbors,NaN,357 Carolina Arbors Drive,Memorial Day Observation\r\n\r\nWould like fir...,100,James,Veterans Club,Social or Community Group,174.109.64.135,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1412,51577,8/7/2019 10:16,NaN,NaN,Berthold,919-699-6805,jamo@gsdurham.com,8/25/2019 15:00,NaN,NaN,...,Bull City Day,NaN,2601 Hillsborough Rd,It is for the neighborhood and church to get t...,100-200,Jamison,Greystone Curch,Church,104.169.24.153,https://durhamnc.gov/FormCenter/Fire-Departmen...
1788,67367,4/6/2021 21:57,NaN,NaN,Daniels,513-227-8454,Rebeccaldaniels@aol.com,4/22/2021 18:30,NaN,NaN,...,Girl Scout Troop 810 fire station visit,NaN,Fire station- near 27701?,My Girl Scout troop of K-3rd graders would lik...,"9 girls, 3 adults",Rebecca,Girl Scouts,Social or Community Group,162.251.57.91,https://durhamnc.gov/FormCenter/Fire-Departmen...
957,46356,6/21/2018 11:41,NaN,NaN,Cole-McFadden,910 614-4756,africancora@aol.com,8/18/2018 11:00,NaN,NaN,...,Youth Explosion,NaN,1901 Athens Street,community youth celebration,50,Cora,West Durham Baptist Church,Church,50.111.44.47,http://nc-durham.civicplus.com/FormCenter/Fire...
3350,360734,9/25/2025 12:22,NaN,NaN,Lyman,7047989444,hannah_lyman@dpsnc.net,3/13/2026 8:00,NaN,NaN,...,Eastway Elementary Career Day,NaN,610 N Alston Avenue,Career Day for K-5 elementary school. Will do ...,325,Hannah,Eastway Elementary,School,174.109.91.112,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2930,322868,9/23/2024 14:28,NaN,NaN,Mitchell,803-840-4384,kkcdcteachers@gmail.com,10/11/2024 10:00,NaN,NaN,...,Fire Safety Week Finale,NaN,1914 NC-55,This will be the end of our Fire Safety Week. ...,27,Alexxis,King's Kids CDC,School,71.69.197.157,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1310,50046,4/25/2019 10:03,NaN,NaN,Smith,919-450-0080,am.village@irtliving.com,5/22/2019 18:00,NaN,NaN,...,Fire & Ice,NaN,801 E Woodcroft Parkway,Join our local fire department for info on fir...,50 - 75,TeJay,The Village at Auburn,Business,107.13.134.235,https://durhamnc.gov/FormCenter/Fire-Departmen...
3168,345255,5/18/2025 12:29,NaN,NaN,Dunn,5018311789,joannemdunn@gmail.com,7/4/2025 10:00,NaN,NaN,...,Falconbridge Neighborhood July 4th Parade,NaN,Huntingridge Rd and Knotty Pine Dr,Neighborhood July 4th parade led by a fire tru...,Fifty,Joanne,Falconbridge Neighborhood Alliance,Social or Community Group,99.45.69.222,https://www.durhamnc.gov/FormCenter/Fire-Depar...
305,17822,7/5/2016 12:25,Triangle Nonprofit & Volunteer Leadership Center,NaN,Rich,9196811835,youth@thevolunteercenter.org,7/27/2016 15:15,NaN,Durham,...,NaN,NaN,2012 E. Club Blvd.,NaN,8,John,NaN,NaN,152.3.253.163,http://nc-durham.civicplus.com/FormCenter/Fire...
1381,51232,7/12/2019 7:24,NaN,NaN,Dufur,919-527-5366,mdufur@aeriepharma.com,8/20/2019 9:30,NaN,NaN,...,Company Fire Extinguisher safety training,NaN,"4301 Emperor Blvd, Durham",Training of 70 personnel in he use of a fire e...,70,Mark,aerie Pharma,NaN,64.132.139.242,https://durhamnc.gov/FormCenter/Fire-Departmen...
3029,332388,1/6/2025 9:52,NaN,NaN,Slavin,9193235121,jack.slavin@duke.edu,2/20/2025 17:00,NaN,NaN,...,Duke Women's Basketball Hero Day,NaN,"110 Whitford Dr., Durham, NC",Duke Women's Basketball is hosting Hero Day on...,2000+,"Jack ""Bull""",Duke Athletics,School,152.3.34.83,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1765,65450,2/3/2021 10:18,NaN,NaN,Leifer,908 295 2061,pleifer@aol.com,3/27/2021 10:00,NaN,NaN,...,Creekside At Beth Page Car Parade,NaN,6609 Crown Parkway,"Parade through neighborhood, led by Fire truck",30,Paul,NaN,Social or Community Group,74.219.16.122,https://durhamnc.gov/FormCenter/Fire-Departmen...
1861,72641,8/23/2021 12:52,NaN,NaN,Kershing,3363401818,jasmynkershing@gmail.com,9/4/2021 9:00,NaN,NaN,...,Fire Station Tour,NaN,3700 Swarthmore Road,"Toddlers visit to fire station, safety/awarene...",3,Jasmyn,NaN,Social or Community Group,45.37.78.139,https://durhamnc.gov/FormCenter/Fire-Departmen...
2024,80833,4/26/2022 14:38,NaN,NaN,Weber,919.641.2545,bweber@measinc.com,7/4/2022 9:30,NaN,NaN,...,"Durham Central Park, 4th of July Children's Pa...",NaN,501 Foster St,Children decorate their bikes and wagons and t...,500,Ben,Durham Central Park,Social or Community Group,64.246.215.5,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3117,341072,4/7/2025 17:00,NaN,NaN,Roane,9196727476,sroane@fcrinc.org,5/16/2025 13:00,NaN,NaN,...,FCR Family Fun Day,NaN,750 Stadium Drive,This event is a fun day for families enrolled ...,400,Sharon,"Families & Communities Rising, Inc",Social or Community Group,66.26.111.242,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1901,73925,9/30/2021 10:38,NaN,NaN,Collins,9195443311,ddurhamnc@goddardschools.com,10/7/2021 10:30,NaN,NaN,...,Community Helper Day,NaN,"5300 Fayetteville Road, 5300 FAYETTEVILLE RD",The Goddard School of Durham\r\n\r\nThe attend...,50+,DeAntony,The Goddard School Durham/Jan Thorne,Business,45.37.92.27,https://durhamnc.gov/FormCenter/Fire-Departmen...
2424,102772,6/12/2023 10:13,NaN,NaN,Holts,5678681415,chelsey.bentley13@gmail.com,7/1/2023 9:00,NaN,NaN,...,Hardscrabble Fourth of July Parade,NaN,102 Hardscrabble Drive,Neighborhood parade for fourth of July,200,Chelsey,NaN,Social or Community Group,152.23.211.96,https://www.durhamnc.gov/FormCenter/Fire-Depar...
743,34809,9/29/2017 13:57,NaN,NaN,Beveridge,919-682-0867,elcdirector@gormanbc.org,10/27/2017 9:15,NaN,NaN,...,Fall Fun Day,10:45 AM,"3311 East Geer Street, Durham, NC",3 groups of kids ages 2 year old- 2nd grade;\r...,70,Amanda,Gorman Early Learning Center,School,24.106.189.50,http://durhamnc.gov/FormCenter/Fire-Department...
594,32743,5/23/2017 10:29,Emmanuel AME Church,NaN,Jackson,919.599.3352,NaN,8/1/2017 17:00,NaN,Durham,...,NaN,NaN,Fayetteville St @ Cook Rd. (Open lot across fr...,NaN,75,Barry,NaN,NaN,161.69.123.11,https://durhamnc.gov/FormCenter/Fire-Departmen...
2454,105990,7/11/2023 10:22,NaN,NaN,Johnson,2029097197,sherardjohnson@gmail.com,8/20/2023 15:00,NaN,NaN,...,Project 300,NaN,"2722 E Main St, Durham, NC",Project 300 is a community back to school even...,500,Sherard,"Ron N Shoot (RNS) Sports, Inc.",Social or Community Group,24.106.176.74,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2164,85587,9/14/2022 10:39,NaN,NaN,Cooper,919-633-8847,rtc23@icloud.com,9/17/2022 11:00,NaN,NaN,...,Shaw University Youth Day,NaN,750 Stadium Dr,Youth event sponsored by Shaw University. Ath...,3000,Regi,Shaw University,School,66.195.223.214,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2225,86568,10/13/2022 14:50,NaN,NaN,Taylor,919-226-0043,sarah.spah@gmail.com,11/16/2022 17:00,NaN,NaN,...,Fire Extinguisher Training,NaN,5601 Fayetteville Road,We would like for the staff to be trained on f...,30,Sarah,Southpoint Animal Hospital,Business,108.169.154.114,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1969,78423,2/11/2022 7:48,NaN,NaN,Watkins,336-269-3626,brandon_watkins@dpsnc.net,3/25/2022 8:00,NaN,NaN,...,Githens Middle School Career Day,NaN,4800 Old Chapel Hill Rd,Career Day for middle school students to intro...,150,Brandon,Sherwood Githens Middle School,School,198.85.255.10,https://durhamnc.gov/FormCenter/Fire-Departmen...
1379,51123,7/7/2019 1:57,NaN,NaN,Peoples,919-638-7984,akisscares@outlook.com,8/3/2019 12:00,NaN,NaN,...,A Kiss Cares Back to School/Community Fair,NaN,1410 Englewood Ave,"This is an event where we give out food, backp...",150,Ebony,A Kiss Cares,Social or Community Group,174.109.93.73,https://durhamnc.gov/FormCenter/Fire-Departmen...
1971,78636,2/17/2022 13:50,NaN,NaN,James,9194518407,clare_james@dpsnc.net,4/14/2022 17:30,NaN,NaN,...,EagleFest at Eno Valley Elementary School,NaN,117 Milton Road,"Eaglefest, is Eno Valley's spring carnival. We...",300,Clare,Eno Valley Elementary School,School,128.109.10.35,https://durhamnc.gov/FormCenter/Fire-Departmen...
1179,48241,11/28/2018 14:59,NaN,NaN,Pearson,9172261792,jeninepearson@fit4mom.com,1/10/2019 11:00,NaN,NaN,...,FIT4MOM Fire Station Tour,NaN,Closest to Southpoint Mall,We'd like to do a station tour for our toddler...,15-Oct,Jenine,FIT4MOM,Social or Community Group,96.10.225.162,http://durhamnc.gov/FormCenter/Fire-Department...
1940,74827,10/31/2021 11:09,NaN,NaN,Wilson,919-609-3403,wilsonb90@icloud.com,11/11/2021 10:30,NaN,NaN,...,We Honor Veterans Drive By Parade,NaN,4434 Ben Franklin Blvd,Kindred Hospice is organizing a drive by parad...,30 total,Britany,Kindred Hospice of Oxford,Business,128.136.33.68,https://durhamnc.gov/FormCenter/Fire-Departmen...
1932,74671,10/25/2021 20:47,NaN,NaN,Parks,919-560-3967,michelle_parks@dpsnc.net,12/3/2021 11:30,NaN,NaN,...,R.N. Harris School,NaN,1520 Cooper Streeet,We would like to have Sparky the fire dog ple...,60 students,Michelle,R.N. Harris,School,50.111.49.238,https://durhamnc.gov/FormCenter/Fire-Departmen...
2314,93681,2/16/2023 17:41,NaN,NaN,Simpson,919-.384-2803,Deons@umrh.org,3/7/2023 8:00,NaN,NaN,...,Fire Extinguisher Training,NaN,2600 Croasdaile Farm Parkway Durham,Annual Fire Extinguisher training for senior l...,75,Deon,Croasdaile Village,Business,155.130.130.200,https://www.durhamnc.gov/FormCenter/Fire-Depar...
498,28594,2/10/2017 19:30,The Frederick A. Edgerton Jr Foundation,NaN,Garris,984-244-0018,mrfredfoundation@gmail.com,6/17/2017 13:30,NaN,Durham,...,NaN,NaN,Hillside Park 1300 South Roxboro Risd,NaN,500,Tiffany,NaN,NaN,107.77.233.69,https://durhamnc.gov/FormCenter/Fire-Departmen...
1968,78331,2/9/2022 11:26,NaN,NaN,Marley,9196806262,meredith@shimar.com,4/7/2022 8:00,NaN,NaN,...,Shimar Monthly Safety Meeting,NaN,938 Harvest Rd.,Provide employees with proper training of a fi...,14,Meredith,"Shimar Recycling, Inc.",Business,24.106.207.149,https://durhamnc.gov/FormCenter/Fire-Departmen...
2646,292910,12/18/2023 11:59,NaN,NaN,Thompson,4084779873,alison.thompson@analog.com,2/27/2024 9:30,NaN,NaN,...,Fire Extinguisher Training for the Workplace E...,NaN,4001 NC Hwy 54 Suite 3100,The fire extinguisher training is intended on ...,20,Alison,"Analog Devices, Inc.",Business,204.17.143.20,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3113,340577,4/1/2025 14:07,NaN,NaN,Curtis,9197974588,Lollipopkidscamp@gmail.com,6/30/2025 9:00,NaN,NaN,...,Summer camp visit,NaN,3218 N. Roxboro st,Low income summer camp and wanted the kids to ...,30,Keisha,Lollipop Kids camp,Social or Community Group,24.163.77.189,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2790,310701,6/11/2024 19:26,NaN,NaN,Chambers,865-322-1339,Chambers.staci@gmail.com,7/4/2024 10:00,NaN,NaN,...,Penrith neighborhood July 4th parade,NaN,Middleton and Kenmont,Annual July 4th parade. We start at the top of...,50,Staci,NaN,Social or Community Group,69.218.220.244,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2044,81638,5/24/2022 11:09,NaN,NaN,Leo,9195197984,Jackie.leo19@yahoo.com,6/9/2022 19:00,NaN,NaN,...,Family fun day,NaN,1230 Carpenter Fletcher Road,My daughter is 7 years old and wants to know m...,4,Jackeline,NaN,Social or Community Group,50.111.120.161,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1114,47640,10/2/2018 14:57,NaN,NaN,Martin,919-360-0646,melody.martin@dpsnc.net,10/24/2018 9:30,NaN,NaN,...,Spring Valley Elementary School Visit,NaN,2051 Northern Durham Parkway,kindergarten classes would see the truck and m...,110,Melody,Spring Valley Elementary,School,70.61.92.170,http://nc-durham.civicplus.com/FormCenter/Fire...
3140,342498,4/23/2025 15:45,NaN,NaN,Wilson,9199249069,hbwilson38@gmail.com,4/25/2025 16:30,NaN,NaN,...,Night on the Lawn,NaN,"3727 Fayetteville St. Durham,",Our school will be hosting an after school eve...,20,Hannah,Durham School of Technology,School,152.22.53.25,https://www.durhamnc.gov/formcenter/fire-depar...
1928,74441,10/17/2021 17:16,NaN,NaN,Wiener,9194524838,ehwiener21@gmail.com,10/31/2021 15:30,NaN,NaN,...,Hope Valley Neighborhood Association Halloween...,NaN,3817 Somerset,We have decided to hold our annual Halloween P...,100?,Elisabeth,Elisabeth Wiener,Social or Community Group,71.69.185.178,https://durhamnc.gov/FormCenter/Fire-Departmen...
32,700,9/14/2015 10:24,the little school at duke,NaN,swanson,919 354 6600,mary@tlsduke.com,9/21/2015 10:00 AM to 9/25/2015 10:00 AM,NaN,durham,...,NaN,NaN,1516 hull ave,NaN,130,mary,NaN,NaN,66.83.209.130,http://durhamnc.gov/FormCenter/Fire-Department...
1722,58262,9/15/2020 20:16,NaN,NaN,Murray (Secretary),919-381-4536 / 410-336-2493,danmurr13@gmail.com,11/11/2020 11:00,NaN,NaN,...,Carolina Arbors' Veterans Day (Nov. 11th) Golf...,NaN,357 Carolina Arbors Drive,Annual parade around our community lasts about...,"30 vehicles - golf carts, bikes, trikes,cars",Daniel,Carolina Arbors Veterans Club,Social or Community Group,50.55.49.27,https://durhamnc.gov/FormCenter/Fire-Departmen...
494,28452,2/8/2017 12:08,First Calvary Baptist Church,NaN,Newsome,919-219-1315,djgadget1@ymail.com,4/15/2017 9:00,NaN,Durham,...,NaN,NaN,1311 Morehead ave,NaN,100,Alvin,NaN,NaN,107.13.128.154,http://durhamnc.gov/FormCenter/Fire-Department...
955,46324,6/19/2018 14:18,NaN,NaN,Ubaldo,919-790-6127,vubaldo@univision.net,9/16/2018 14:00,NaN,NaN,...,UniRumba - grassroots event that emphasizes th...,NaN,2000 Avondale Drive,This will be a family event with an expected a...,5000,Victor,Univision,Business,70.61.92.170,http://nc-durham.civicplus.com/FormCenter/Fire...
3398,363541,10/20/2025 11:49,NaN,NaN,Cristofoli,984-241-3040,jessicacr@kindbh.com,11/1/2025 10:00,NaN,NaN,...,Trunk or Treat / Fall Fest,NaN,"1012 Slater Road, Durham, NC",Kind Behavioral Health (KBH) in Durham is host...,30,Jessica,Kind Behavioral Health,Business,99.78.73.205,https://www.durhamnc.gov/FormCenter/Fire-Depar...
299,17743,7/2/2016 11:58,Northgate Park Neighborhood Association,NaN,Kneepkens,919-824-5946,nkneep@earthlink.net,8/2/2016 17:00,NaN,Durham,...,NaN,NaN,"Northgate Park, corner of 300 block of W. Lave...",NaN,NaN,Nancy,NaN,NaN,24.40.136.93,http://nc-durham.civicplus.com/FormCenter/Fire...
282,16824,6/18/2016 18:00,Southern States Volkswagen,NaN,Alexander,9196568370,talexanderatwork@gmail.com,7/2/2016 11:00,NaN,Durham,...,NaN,NaN,3823 Durham Chapel Hill Blvd,NaN,50,Tracy,NaN,NaN,96.10.13.243,https://durhamnc.gov/FormCenter/Fire-Departmen...
2957,323994,10/3/2024 12:00,NaN,NaN,Vazquez,9514579039,Susette@primrosehopevalleyfarms.com,10/25/2024 18:00,NaN,NaN,...,Fall Festival /Trunk or Treat,NaN,702 Juliette Dr,We are having a Trunk or Treat and thought thi...,100,Susette,Primrose School at Hope Valley Farms,School,136.54.209.157,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1321,50292,5/14/2019 11:42,NaN,NaN,Hiles,919-564-8025,eventsatparkwoodnc.org,8/6/2019 18:00,NaN,NaN,...,Parkwood NNO,NaN,1417 Seaton Road - HOA facility,Parkwood NNO Event,100,Hannah,Parkwood HOA,Social or Community Group,66.195.223.214,https://durhamnc.gov/FormCenter/Fire-Departmen...
1826,70706,6/25/2021 10:56,NaN,NaN,Farrow,919-956-4522,tawana.farrow@duke.edu,8/9/2021 12:00,NaN,NaN,...,Community Health Center Week,NaN,"1301 Fayetteville Street, Durham NC",Annual celebration with the goal of raising aw...,Unknow,Tawana,Lincoln Community Health Center,Business,204.116.38.98,https://durhamnc.gov/FormCenter/Fire-Departmen...

In [190]:
print(df.columns.tolist())

['ID', 'Submission Date', 'Organization Name', 'Your First Name', 'Last Name', 'Phone Number', 'Email Address', 'Desired Date & Time of Event', 'Address of Event', 'City', 'State', 'Zip Code', 'Total Number of Children, Adults or both Participating in the Event', 'Fire Safety/Fire Prevention Programs', 'Additional Request or Questions?', 'Available Sations for Tour', 'Fire Safety/Fire Prevention Programs.1', 'Available Stations for Tour', 'Name of Event', 'End Time of the Event', 'Street Address of Event', 'Event Description', 'Anticipated Number of Participants', 'First Name', 'Agency Name', 'Type of Agency', 'IP Address', 'Referrer']

#### Data Cleaning

In [191]:
# Ensuring datetime type
df["Submission Date"] = pd.to_datetime(df["Submission Date"])

# Splitting into separate columns
df["Date of Submission"] = df["Submission Date"].dt.date.astype(str)   # YYYY-MM-DD
df["Time of Submission"] = df["Submission Date"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Submission Date"])

# Moving new columns to the front
cols = ["Date of Submission", "Time of Submission"] + [c for c in df.columns if c not in ["Date of Submission", "Time of Submission"]]
df = df[cols]

In [192]:
# Dropping unnecessary columns
df = df.drop(columns=["ID", "Your First Name", "Last Name", "Phone Number", "Email Address",
                     "Desired Date & Time of Event", "Address of Event", "City", "State", "Zip Code", 
                      "Total Number of Children, Adults or both Participating in the Event",
                     "Fire Safety/Fire Prevention Programs", "Additional Request or Questions?", 
                     "Available Sations for Tour", "Fire Safety/Fire Prevention Programs.1", "Available Stations for Tour", 
                     "End Time of the Event", "First Name", "IP Address", "Referrer", "Event Description", 
                      "Street Address of Event"])
display(df.sample(5))
print(df.columns.tolist())

,Date of Submission,Time of Submission,Organization Name,Name of Event,Anticipated Number of Participants,Agency Name,Type of Agency
1036,2018-08-22,15:39:00,NaN,DPD Grand Opening,500,Durham Police Department,Business
1574,2019-12-13,12:52:00,NaN,The Learning Experience,50,NaN,School
1260,2019-03-19,08:24:00,NaN,DCFMO Fire Safety presentation at Sandy Ridge ...,100,Durham County Fire Marshal's Office,Government
2308,2023-02-13,11:10:00,NaN,Community Day Event,50,New Jerusalem Baptist Cathedral,Church
104,2015-10-19,09:59:00,Family Preschool,NaN,45,NaN,NaN

['Date of Submission', 'Time of Submission', 'Organization Name', 'Name of Event', 'Anticipated Number of Participants', 'Agency Name', 'Type of Agency']

In [193]:
# Converting date column into datetime format
df["Date of Submission"] = pd.to_datetime(df["Date of Submission"], errors="coerce")

# Cleaning participant values by extracting and normalising numbers
def clean_participants(text):
    if pd.isna(text):
        return np.nan

    text = str(text).lower()

    # removing commas in numbers like 1,000
    text = text.replace(",", "")

    # extracting all numeric values
    nums = re.findall(r'\d+(?:\.\d+)?', text)
    nums = [float(n) for n in nums] if nums else []

    if len(nums) == 0:
        return np.nan

    # handling "less than X"
    if "less than" in text:
        return nums[0]

    # handling ">" or "+"
    if ">" in text or "+" in text:
        return nums[0]

    # handling ranges like 50-100 or 50 - 100
    if "-" in text and len(nums) >= 2:
        return sum(nums[:2]) / 2

    # handling multiple groups like "15 children 5 adults"
    # or "33 students/9 teachers"
    if len(nums) > 1:
        return sum(nums)

    # returning single numeric values
    return nums[0]


# applying cleaning function
df["Participants_Clean"] = df["Anticipated Number of Participants"].apply(clean_participants)

# removing rows with missing participant values
df = df.dropna(subset=["Participants_Clean"])

# filtering only 2025 and 2026 rows
df = df[df["Date of Submission"].dt.year.isin([2025, 2026])]

# sorting by date in descending order
df = df.sort_values("Date of Submission", ascending=False)

# splitting into yearly dataframes
df_2025 = df[df["Date of Submission"].dt.year == 2025].copy()
df_2026 = df[df["Date of Submission"].dt.year == 2026].copy()

# renaming columns in both datasets
for d in [df_2025, df_2026]:
    d.rename(columns={
        "Date of Submission": "Submission Date",
        "Time of Submission": "Submission Time"
    }, inplace=True)
    
# Displaying 50-row samples for 2025 and 2026 datasets
display(df_2025.sample(50))
display(df_2026.sample(50))

,Submission Date,Submission Time,Organization Name,Name of Event,Anticipated Number of Participants,Agency Name,Type of Agency,Participants_Clean
3367,2025-10-02,13:39:00,NaN,Fire Prevention at The Whitted School,80,Whitted School - Durham Public Schools,School,80.0
3331,2025-09-16,15:04:00,NaN,Fire Prevention: Center/Classroom Visit,30,Linking Connections Learning,School,30.0
3274,2025-08-22,13:41:00,NaN,Emorywood Orchards Community Fall Event,50,Emorywood Orchards,Social or Community Group,50.0
3303,2025-09-03,16:05:00,NaN,Pre-Kindergarten Field trip,50 children,Abundant Love Christian Daycare,School,50.0
3309,2025-09-05,12:11:00,NaN,Fire Department Visit,30,Community Preschool at Lakewood,School,30.0
3032,2025-01-10,18:18:00,NaN,I'd like to Photograph the Durham Fire Department,1,Kyle Foreman Photography,Business,1.0
3335,2025-09-19,09:04:00,NaN,Meeting our Community Helpers,20,Hope Valley Elamentayr,School,20.0
3053,2025-02-07,08:18:00,NaN,School-Age field trip,25,NaN,School,25.0
3306,2025-09-04,13:39:00,NaN,Fire Prevention Week,15,Y. E. Smith (DPS),School,15.0
3361,2025-09-30,08:43:00,NaN,2nd Grade Durham Academy visit to the Fire Sta...,40,Durham Academy Lower School,School,40.0
3346,2025-09-24,10:46:00,NaN,Community Helpers,45,Westminster School for Young Children,School,45.0
3408,2025-10-30,08:44:00,NaN,Fire station tour,2,NaN,NaN,2.0
3310,2025-09-05,13:03:00,NaN,Preschool Class visits/tours/experience at our...,"35 3-5 year olds, 15 1-2 year olds in a separa...","Family Preschool (in the ERUUF church, with pa...",School,19.0
3411,2025-10-30,11:08:00,NaN,Fire Safety,16,Al Qalam Triangle Academy,School,16.0
3251,2025-08-11,10:15:00,NaN,Effects of Fentanyl on First Responders: can g...,10,North Carolina Central University,Government,10.0
3234,2025-07-24,13:52:00,NaN,Fire Extinguisher Training,50,HemoSonics LLC,Business,50.0
3372,2025-10-06,12:58:00,NaN,Lowes Fire Safety Event,50,Lowes,Business,50.0
3342,2025-09-23,13:00:00,NaN,Almac Family Fun Day,300,Almac Group,Business,300.0
3213,2025-07-09,13:28:00,NaN,Public Safety Day,50,Faith Community Church/Summer Camp,Church,50.0
3125,2025-04-11,12:36:00,NaN,BHUC Fun Day,7,Carolina Outreach,Business,7.0
3177,2025-05-23,14:05:00,NaN,RAMA SUMMER PROGRAM,20,REACHING ALL MINDS ACADEMY,School,20.0
3283,2025-08-27,17:32:00,NaN,McMannen Preschool Visit,"20 children, 6 adults",McMannen Preschool,School,26.0
3245,2025-08-06,09:34:00,NaN,Durham Oktoberfest,500,The Glass Jug Beer Lab,Business,500.0
3131,2025-04-17,15:49:00,NaN,Maureen Joy Kindergarten Classroom Visit,65,Maureen Joy Charter School,School,65.0
3186,2025-06-02,15:47:00,NaN,Eno Trace 4th of July Bike parade,50,Eno Trace HOA,Social or Community Group,50.0
3385,2025-10-13,11:08:00,NaN,Chancellor's Ridge Neighborhood Oktoberfest,300,NaN,Social or Community Group,300.0
3145,2025-04-30,23:06:00,NaN,Church Children’s Activity,15,Church of Jesus Christ of Latter-day Saints,Church,15.0
3067,2025-02-20,15:50:00,NaN,CAREER FAIR 2025,300,Burton Magnet Elementary School,School,300.0
3277,2025-08-25,09:26:00,NaN,National Night Out Day Block Party,100,Elite Management Professionals,Business,100.0
3446,2025-12-22,11:17:00,NaN,Girl Scouts Station Visit,20,Girl Scouts,Social or Community Group,20.0
3219,2025-07-15,15:52:00,NaN,Northgate Park National Night Out,50-100,Northgate Park Neighborhood Association,Social or Community Group,75.0
3333,2025-09-18,12:20:00,NaN,Barktoberfest,2400,Durham Parks and Recreation,Government,2400.0
3106,2025-03-27,12:39:00,NaN,Syngenta Fire Extinguisher Training,40,"Syngenta Crop Protection, LLC.",Business,40.0
3208,2025-06-27,10:36:00,NaN,Fire station tour,3,NaN,NaN,3.0
3104,2025-03-27,09:25:00,NaN,LInde Gas & Equipment Safety Day,50,Linde Gas & Equipment,Business,50.0
3419,2025-11-04,11:16:00,NaN,Dream Big Book Drive & Community Celebration,"1,000+",Book Harvest,Social or Community Group,1000.0
3228,2025-07-18,14:18:00,NaN,Fire Truck Display at Child Care Center,125,Duke University Health System OESO Fire & Life...,School,125.0
3185,2025-06-02,14:38:00,NaN,76th Annual Watts Hospital-Hillandale Neighbor...,300-500,Watts Hospital-Hillandale Neighborhood Associa...,Social or Community Group,400.0
3257,2025-08-14,10:16:00,NaN,Community Helpers: Fire Safety Week (Theme for...,"12 children, 2 adults",Durham Public Schools,School,14.0
3074,2025-02-26,16:53:00,NaN,Grand Opening and Ribbon Cutting,100-200,Immanuel Temple Seven Day Adventist Church,Church,150.0
3366,2025-10-01,12:18:00,NaN,NORTHGATE PARK NNO,30-55,NGP,Social or Community Group,42.5
3199,2025-06-19,23:21:00,NaN,Downing Creek 4th of July Parade,75,NaN,Social or Community Group,75.0
3202,2025-06-23,13:27:00,NaN,"Fire Safety, Residential Assistant Training",90,Residential Life,School,90.0
3153,2025-05-07,14:52:00,NaN,Career Day,25,Liberty Christian School,School,25.0
3264,2025-08-18,10:02:00,NaN,Pre-K Fire Truck Visit,50,"Toddlers Academy, Inc.",School,50.0
3389,2025-10-14,13:23:00,NaN,ESA II Fire Safety Month,40,ESA II,School,40.0
3340,2025-09-23,08:56:00,NaN,Fire Prevention Week Visit,150,Children's Campus at Southpoint,School,150.0
3204,2025-06-24,09:46:00,NaN,National First Responders Day. I will have a l...,30,Durham Parks and Recreation,Government,30.0
3373,2025-10-07,11:42:00,NaN,Fire Prevention/ Crime Prevention,30,NaN,School,30.0
3334,2025-09-18,16:24:00,NaN,Mount Level Missionary Baptist Church's Commun...,100-200,"Mount Level Missionary Baptist Church Durham, NC",Church,150.0

,Submission Date,Submission Time,Organization Name,Name of Event,Anticipated Number of Participants,Agency Name,Type of Agency,Participants_Clean
3487,2026-02-26,12:38:00,NaN,Community Health Festival,1000,Community Health Coalition,Business,1000.0
3570,2026-05-13,12:54:00,NaN,SoDu Anniversary at Hub RTP,300-400,South Durham Farmers' Market,Business,350.0
3514,2026-03-18,15:19:00,NaN,Falconbridge 4th of July celebration,50,Falconbridge Alliance and FHA,Social or Community Group,50.0
3506,2026-03-10,12:29:00,NaN,Fire Extinguisher Training for FF I Students,16 (1st round) 12 (2nd round),Durham Public Schools / Northern High School,School,31.0
3492,2026-03-04,13:09:00,NaN,Calvary Festival Family Fun Day-Community Day ...,500-1000,First Calvary Baptist Church,Church,750.0
3516,2026-03-19,14:34:00,NaN,Community Day,200,Moreloveecp,Social or Community Group,200.0
3496,2026-03-06,11:13:00,NaN,Durham Academy Summer Programs,30-40,Durham Academy Summer,School,35.0
3508,2026-03-12,10:09:00,NaN,"""When I Grow Up"" ( Community Workers week)",20-30,International Montessori School- Academy Rd ca...,School,25.0
3472,2026-02-09,13:29:00,NaN,Fire Station Tour,28,NaN,School,28.0
3549,2026-04-24,12:08:00,NaN,Duke School's Safety Spark-Tacular,100,Duke School,School,100.0
3499,2026-03-07,11:31:00,NaN,National Night Out,75,Grove Park HOA,Social or Community Group,75.0
3537,2026-04-09,09:32:00,NaN,"Dukes in Motion: Firefighter Day (hoses, gear,...",20,Dukes in Motion,Social or Community Group,20.0
3557,2026-04-29,14:51:00,NaN,Summer Camp,24,Hope Valley Country Club,Business,24.0
3574,2026-05-14,16:07:00,NaN,Hands-On Only CPR,15 - 20,GoDurham,Business,17.5
3546,2026-04-21,10:26:00,NaN,FPDC Safety Week-Fire Extinguisher Training,40-50,Duke Health FPDC (Facilities Planning Design &...,Business,45.0
3577,2026-05-15,15:16:00,NaN,Touch a Truck Event,30,NaN,NaN,30.0
3519,2026-03-23,10:24:00,NaN,EK Powe Career Day,400,E.K. Powe,School,400.0
3505,2026-03-09,20:12:00,NaN,Springfest,75,Charleston Management Group - Chamberlynne,Social or Community Group,75.0
3573,2026-05-14,16:05:00,NaN,CPR Hands Only,15 - 20,GoDurham,Business,17.5
3501,2026-03-07,16:22:00,NaN,ABCs of Community Readiness,>100,Queerolina,Social or Community Group,100.0
3460,2026-01-22,06:29:00,NaN,LABOR IN LOVE,60,NC AFL-CIO’s Triangle Labor Council/Durham NC ...,Social or Community Group,60.0
3569,2026-05-11,16:12:00,NaN,Eno Trace 4th of July Bike Parade,50,NaN,Social or Community Group,50.0
3529,2026-03-31,20:46:00,NaN,Bimbe Block Party,400,Durham Parks and Recreation,School,400.0
3582,2026-05-18,11:39:00,NaN,Child Safety Week,150,Kids 'R' Kids RTP,School,150.0
3494,2026-03-05,10:27:00,NaN,Career Day,200,Murray Massenburg,School,200.0
3510,2026-03-15,15:44:00,NaN,Hazmat Decon Practical Skills,10,Durham Public Schools / Northern High School,School,10.0
3482,2026-02-22,15:56:00,NaN,Community Helpers Week,"The preschool class has 18 children, but we’d ...",Brittney Mitchell,School,18.0
3522,2026-03-24,11:05:00,NaN,FCR Family & Community Fest,500,www.fcrinc.org,School,500.0
3542,2026-04-16,14:09:00,NaN,Unifirst Durham Annual Fire Drill,75,UniFirst,Business,75.0
3471,2026-02-09,10:16:00,NaN,Preschool Visit,90,Create Great Minds,School,90.0
3451,2026-01-12,12:08:00,NaN,Grove Park July 4th Parade,50-75,USSA,Social or Community Group,62.5
3554,2026-04-27,19:48:00,NaN,Safety Week,30,Kids Korner Academy II,School,30.0
3461,2026-01-26,08:17:00,NaN,Little Heroes Visit the Fire Station,8 people,Jack and Jill of America- Durham Chapter,Social or Community Group,8.0
3533,2026-04-06,10:30:00,NaN,Preschool Visit,95 children,Our PlayHouse Preschool,School,95.0
3532,2026-04-01,14:27:00,NaN,Logan’s 4th birthday party,15 kids,NaN,NaN,15.0
3583,2026-05-19,12:14:00,NaN,Birthday fire truck tour,10-May,NaN,NaN,10.0
3500,2026-03-07,11:34:00,NaN,Grove Park Santa Parade,20-40,Grove Park HOA,Social or Community Group,30.0
3571,2026-05-13,15:00:00,NaN,Summer Literacy Initiative,12,Summer Literacy Initative,Social or Community Group,12.0
3539,2026-04-13,13:18:00,NaN,FCCI / Health & Business,15-Oct,Faith Community Church International,Church,15.0
3527,2026-03-29,13:06:00,NaN,Daycare Visit,150,Goddard School-Durham,School,150.0
3474,2026-02-12,09:26:00,NaN,Fire Extinguisher Training,7,"Orchid Bioscience, Inc",Business,7.0
3467,2026-02-03,15:46:00,NaN,George Watts Montessori Spring Carnival,500,George Watts PTA,School,500.0
3572,2026-05-14,15:58:00,NaN,CPR - Hands Only,15 - 20,GoDurham,Business,17.5
3563,2026-05-04,11:26:00,NaN,New Jerusalem's Family and friends Community Day,75,New Jerusalem Community Church,Church,75.0
3511,2026-03-16,14:48:00,NaN,Kestrel Heights Career Day,84,Kestrel Heights Charter School,School,84.0
3478,2026-02-13,16:00:00,NaN,Cub Scout Pack 495 Station Visit,25,Cub Scout Pack 495,Social or Community Group,25.0
3484,2026-02-25,11:26:00,NaN,Ignite! Culture Fest,25 students with a few adult bystanders,Ignite Online Academy (DPS),School,25.0
3470,2026-02-07,16:35:00,NaN,Excelsior Classical Academy Spring Fling,350,NaN,School,350.0
3491,2026-03-03,12:14:00,NaN,Career Day,2,Leo's Foundation Academy,School,2.0
3547,2026-04-21,11:32:00,NaN,Fire Ext training for job site,20 ish,Crescent Communities Construction,Business,20.0