#### Importing Libraries

In [568]:
import pandas as pd
from IPython.display import display
import numpy as np
import os
import re

In [569]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Captain_Burtons/input/form_data_filtered.csv")
display(df.sample(50))

,ID,Submission Date,Organization Name,Your First Name,Last Name,Phone Number,Email Address,Desired Date & Time of Event,Address of Event,City,...,Name of Event,End Time of the Event,Street Address of Event,Event Description,Anticipated Number of Participants,First Name,Agency Name,Type of Agency,IP Address,Referrer
1702,56929.0,8/10/2020 22:04,NaN,NaN,McLandsborough,4048957573,travis.j.mclandsborough@fedex.com,8/11/2020 10:00,NaN,NaN,...,Durham Fedex Annual Fire Drill,NaN,"4357 S, Alston",Annual Fire Drill for the Fedex Ground Durham ...,30-40,Travis,Fedex Ground,Business,199.82.243.89,https://durhamnc.gov/FormCenter/Fire-Departmen...
2534,112488.0,9/15/2023 15:04,NaN,NaN,Scalercio,919-609-3647,trevor.scalercio@hines.com,10/24/2023 10:00,NaN,NaN,...,Hock Plaza Fire Drill,NaN,2424 Erwin Road,Building-wide fire drill.,400,Trevor,Hines,Business,24.106.207.34,https://www.durhamnc.gov/FormCenter/Fire-Depar...
891,45328.0,4/16/2018 10:45,NaN,NaN,Brown,281-961-8774,sbrown@triprop.com,5/19/2018 9:00,NaN,NaN,...,Angelman Syndrome Foundation Walk,NaN,"4309 Emperor Blvd., Durham, NC 27703",This is a walk to raise money and awareness fo...,around 150,Shalanda,Tri Properties,Business,64.132.109.146,https://durhamnc.gov/FormCenter/Fire-Departmen...
838,40298.0,2/22/2018 20:39,NaN,NaN,Conner,919 451 5445,kathy.conner@dpsnc.net,3/23/2018 8:00,NaN,NaN,...,Career Day,NaN,2325 Cheek Road,2325 Cheek Road,200,Kathy,Merrick-Moore,School,162.202.221.0,https://durhamnc.gov/FormCenter/Fire-Departmen...
2419,102121.0,6/5/2023 2:55,NaN,NaN,Ross,9196040747,busymom4god@yahoo.com,7/22/2023 10:00,NaN,NaN,...,Community Day at Lynn's Crossroads Ruritan Club,NaN,4410 Carpenter Pond Rd,"An open house, family fun and education event....",100-300 ?,Geneva,Lynn's Crossroads Ruritan Club,Social or Community Group,98.26.45.31,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1746,61337.0,10/30/2020 6:28,NaN,NaN,Geary,919-641-3592,relaxinginart@gmail.com,11/17/2020 16:00,NaN,NaN,...,The Studios at 1703 Fire Extinguisher Training,NaN,1703 Chapel Hill Road,Fire Extinguisher Training as per conversation...,8,Maria,The Studios at 1703,Social or Community Group,162.202.221.81,https://durhamnc.gov/FormCenter/Fire-Departmen...
2257,87769.0,11/10/2022 16:03,NaN,NaN,Avila,9193215477,rut.avila@durhamnc.gov,12/10/2022 12:00,NaN,NaN,...,Holiday Fun Day,NaN,2000 Avondale Drive,Community day with the shoppers at Compare Foo...,200,Rut,Durham Police Department,Government,166.137.19.17,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3368,361836.0,10/4/2025 10:36,NaN,NaN,Nicoll,9192608983,Manager@southdurhamfarmersmarket.org,10/25/2025 9:00,NaN,NaN,...,Howl-ween at South Durham Farmers’ Market,NaN,"500 Park Offices Dr., Durham, NC",We’ll be hosting Howl-ween at South Durham Far...,50-100,Carlee,South Durham Farmers’ Market,Business,104.28.32.226,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1416,51633.0,8/11/2019 13:54,NaN,NaN,Addy,9199874749,Ceasar_B_Addy@stores.gap.com,9/28/2019 11:00,NaN,NaN,...,Kids Safety Event,NaN,7001 Fayetteville Rd,AT Old Navy we host our Kids Safely Event ever...,100,Ceasar,Old Navy,Business,71.135.1.251,https://durhamnc.gov/FormCenter/Fire-Departmen...
153,9122.0,2/8/2016 13:07,Volunteer Center of Durham,NaN,Clark,919-684-9690,adrienne@thevolunteercenter.org,4/30/2016 8:00,NaN,Blackwell Street,...,NaN,NaN,Durham Bulls Athletic Park,NaN,"1,500",Adrienne,NaN,NaN,152.3.253.175,http://durhamnc.gov/FormCenter/Fire-Department...
474,27235.0,1/17/2017 13:31,Morehead Montessori Elementary School,NaN,Sanders,919 560-3954,margaret.sanders@dpsnc.net,2/17/2017 14:00,NaN,durham,...,NaN,NaN,909 cobbs st,NaN,82 pre-k and kindergarten,Margaret,NaN,NaN,152.26.176.38,https://durhamnc.gov/FormCenter/Fire-Departmen...
2499,110886.0,8/28/2023 13:48,NaN,NaN,Graves,9196970195,nikki.graves@da.org,9/15/2023 10:30,NaN,NaN,...,Durham Academy Preschool Community Helpers Unit,NaN,3501 Ridge Road,Firefighters and Fire Truck visit the preschoo...,36,Nikki,Durham Academy,School,207.235.52.106,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1137,47748.0,10/10/2018 15:30,NaN,NaN,Langhorne,919 544 2815,info@learningtotsacademy.com,10/22/2018 10:00,NaN,NaN,...,Fire Prevention Week,NaN,1900 Sedwick Rd,Preschool fire truck view ages 1-5,70,Lateshia,Learning Tots Academy,School,107.15.226.217,http://nc-durham.civicplus.com/FormCenter/Fire...
994,46743.0,7/16/2018 14:53,NaN,NaN,DIXON,919.560.1647 EXT. 34245,ROBIN.DIXON@DURHAMNC.GOV,9/8/2018 12:00,NaN,NaN,...,Unity and Remembrance with the Bull City,NaN,1058 West Club Blvd,Community Event at Northgate Mall,300,ROBIN,CITY OF DURHAM -NIS,Government,70.61.92.170,http://durhamnc.gov/FormCenter/Fire-Department...
357,20297.0,8/12/2016 15:11,Fellowship Baptist Academy,NaN,Holloway,919-219-6026,rmholloway828@yahoo.com,9/23/2016 13:00,NaN,Durham,...,NaN,NaN,515 Southerland Street,NaN,65,Rhonda,NaN,NaN,45.37.189.163,https://durhamnc.gov/FormCenter/Fire-Departmen...
1039,47235.0,8/27/2018 13:26,NaN,NaN,Williams,919-560-2890,frances.williams@dpsnc.net,10/10/2018 13:00,NaN,NaN,...,Fire Prevention Week,NaN,2051 Northern Durham Pkwy,Would fire prevention presentation for Kinderg...,200,Frances,Spring Valley Elementary,School,152.26.176.26,http://durhamnc.gov/FormCenter/Fire-Department...
1189,48672.0,1/4/2019 11:08,NaN,NaN,BROWN,9842197770,JACKIEBROWN1031@YAHOO.COM,1/9/2019 13:00,NaN,NaN,...,INSTALLION,NaN,120 RIVER RUN ROAD,HOME INSTALLATION,2,JACQUELINE,NaN,NaN,70.61.92.170,http://durhamnc.gov/FormCenter/Fire-Department...
1345,50596.0,6/3/2019 16:17,NaN,NaN,Miller,919 599 7618,tom-miller1@nc.rr.com,7/4/2019 9:45,NaN,NaN,...,70th Annual Watts-Hillandale July 4 Parade,NaN,2200 West Club Boulevard,Annual Independence Day Parade and Celebration...,500,Tom,Watts Hospital-Hillandale Neighborhood Associa...,Social or Community Group,24.163.85.150,https://durhamnc.gov/FormCenter/Fire-Departmen...
1167,48018.0,11/6/2018 8:57,NaN,NaN,Mason,910-489-5513,amason@heritageacedemy-nc.org,11/14/2018 12:15,NaN,NaN,...,Heritage Leadership Academy,NaN,2335 Presidential Drive,Community Helpers,24,Ashley,Heritage Leadership Academy,School,70.61.92.170,http://nc-durham.civicplus.com/FormCenter/Fire...
1376,51096.0,7/3/2019 20:05,NaN,NaN,Rutledge,8036081245,shamekarutledge@aim.com,7/4/2019 20:15,NaN,NaN,...,None,NaN,510 Pebblestone Drive,Smoke detector is beeping after battery was ch...,1,Shameka,NaN,NaN,76.182.9.21,https://durhamnc.gov/FormCenter/Fire-Departmen...
1118,47667.0,10/4/2018 11:18,NaN,NaN,Smith,9198165610,Shaebunnie18@gmail.com,10/19/2018 10:45,NaN,NaN,...,Fire Safety Week,NaN,3807 university dr,Fire safety week for children ages 2-5,30,Carnilla,A New Beginning,Business,99.203.20.155,http://durhamnc.gov/FormCenter/Fire-Department...
1747,61402.0,11/1/2020 21:50,NaN,NaN,MCKOY,9199239851,NaN,11/2/2020 14:45,NaN,NaN,...,Smoke Alarm Installation,NaN,707 OBSIDIAN WAY,Trying to educate guests about the importance ...,4,ROY,Prestige Communications,Church,45.30.222.231,https://durhamnc.gov/FormCenter/Fire-Departmen...
3007,326497.0,10/30/2024 13:44,NaN,NaN,Cassells,9195603944,chantal_cassells@dpsnc.net,12/2/2024 10:00,NaN,NaN,...,Fire Safety House and School Visit,NaN,2905 Fayetteville Street,Classroom Teachers requesting Fire Safety Hous...,40,Chantal,Durham Public Schools-Fayetteville Street Elem...,School,152.22.49.24,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3500,377380.0,3/7/2026 11:34,NaN,NaN,Galberth,9193066183,fhgalberth@gmail.com,12/5/2026 10:00,NaN,NaN,...,Grove Park Santa Parade,NaN,300 Nichols Farm Dr,This is a parade that is led by the Fire Truck...,20-40,Fatina,Grove Park HOA,Social or Community Group,75.207.74.191,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2467,107537.0,7/26/2023 7:51,NaN,NaN,Avila,9193215477,Rut.Avila@durhamnc.gov,8/12/2023 12:00,NaN,NaN,...,Community Day at Compare Foods,NaN,2000 Avondale Drive,Community day in the parking lot. Inform custo...,100,Rut,Durham Police Department,Government,45.27.94.158,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1228,49234.0,2/22/2019 8:09,NaN,NaN,Kaufman,919-560-3944,giselle.kaufman@dpsnc.net,4/8/2019 8:30,NaN,NaN,...,Fayetteville Street Elementary School Career Week,NaN,2905 Fayetteville Street,Grade K-5 are learning about different careers...,grade levels 40 students each grade level,Giselle,Fayetteville Street Elementary,School,152.26.176.26,https://durhamnc.gov/FormCenter/Fire-Departmen...
1274,49656.0,3/26/2019 17:03,NaN,NaN,Thornley,9192206181,ythornley@covenantpropertyservices.com,8/6/2019 17:00,NaN,NaN,...,National Night Out,NaN,1306-C Leon Street,National Night Out,200,Yanisa,Oaks At Northgate Apartments,NaN,70.62.121.54,https://durhamnc.gov/FormCenter/Fire-Departmen...
1570,53222.0,12/9/2019 14:37,NaN,NaN,Oladele,9194751086,doladele@voacarolinas.org,12/30/2019 9:00,NaN,NaN,...,Fire Safety Training,NaN,207 Commons Blvd.,Fire Safety Training for Maple Court residents,24,Daniel,VOA -Maple Court,Social or Community Group,76.182.96.251,https://durhamnc.gov/FormCenter/Fire-Departmen...
177,10118.0,2/25/2016 12:15,Beth El Preschool,NaN,Gudeman,919-688-8704,NaN,5/2/2016 9:30,NaN,Durham,...,NaN,NaN,1004 Watts St.,NaN,50,Lorri,NaN,NaN,174.109.99.125,http://durhamnc.gov/FormCenter/Fire-Department...
2706,300667.0,3/6/2024 17:10,NaN,NaN,Karp,6177804642,rose.chabad@gmail.com,3/24/2024 15:00,NaN,NaN,...,Purim Party at the Jewish Federation,NaN,1937 W Cornwallis Rd,Purim party for the Durham/Chapel Hill communi...,200,Esti,Chabad of Durham-Chapel Hill,Social or Community Group,76.35.65.123,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1229,49251.0,2/25/2019 9:53,NaN,NaN,McNeill,919-885-2168,devin_mcneill90@gmail.com,2/7/2019 9:45,NaN,NaN,...,Fire Safety Awarness,NaN,"3415 S. Alston Ave, Durham, NC",Fire Safety Awareness,20,Devin,Mi Neighborhood Playhouse Too,School,75.189.195.157,https://durhamnc.gov/FormCenter/Fire-Departmen...
3423,365819.0,11/6/2025 13:02,NaN,NaN,Jager,3479983224,rocheljager@gmail.com,12/14/2025 14:00,NaN,NaN,...,Jewish For Good Hanukkah Festival,NaN,1937 W Cornwallis Rd,Annual Hanukkah Festival to celebrate Hanukkah...,650,Rochel,Chabad of Durham-Chapel Hill,Social or Community Group,98.116.142.144,https://www.durhamnc.gov/FormCenter/Fire-Depar...
885,45271.0,4/11/2018 16:18,NaN,NaN,Medley,9192866601,ryan.medley@hines.com,5/22/2018 11:00,NaN,NaN,...,Hock Plaza fire drill,NaN,2424 Erwin Road,Annual building-wide fire drill at Hock Plaza,"1,000",Ryan,Hines,Business,24.106.207.34,https://durhamnc.gov/FormCenter/Fire-Departmen...
700,34523.0,9/11/2017 21:15,NaN,NaN,Oldham,9195481416,aoldham@myhsa.net,9/26/2017 11:00,NaN,NaN,...,Healthy Start Academy Autumn Fest,3:00 PM,807 W Chapel Hill St,"Fall festival with food, games, crafts, etc., ...",250,Autumn,Healthy Start Academy,School,71.51.252.122,https://durhamnc.gov/FormCenter/Fire-Departmen...
792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,35040.0,10/17/2017 15:09,NaN,NaN,Travis,910 574 7693,travisbyar@gmail.com,10/21/2017 16:00,NaN,NaN,...,Oakhaven Neighborhood Celebration,5:00 PM,"901 Martry Drive, Durham, NC",Oakhaven Community celebration and get together.,35,Jim,NaN,Social or Community Group,107.15.228.79,http://durhamnc.gov/FormCenter/Fire-Department...
1990,79575.0,3/16/2022 11:30,NaN,NaN,DINKINS,15716349186,s.dinkins@ktssolutions.com,4/17/2022 11:00,NaN,NaN,...,KTS SOLUTIONS,NaN,2921 GUESS ROAD,KTS SOLUTIONS FIRE EXTINGUISHER,15,SHUNDRA,KTS SOLUTIONS,Business,2603:6080:6504:b4c7:608e:2c25:d237:c064,https://www.durhamnc.gov/FormCenter/Fire-Depar...
92,2298.0,10/8/2015 14:48,Nimble Storage,NaN,Slyter,9193285769,Darcy.Slyter@nimblestorage.com,10/9/2015 9:30 AM to 10/9/2015 9:45 AM,NaN,Durham,...,NaN,NaN,1015 Swabia Ct.,NaN,0,Darcy,NaN,NaN,64.47.70.50,http://nc-durham.civicplus.com/FormCenter/Fire...
430,23277.0,10/6/2016 7:05,W. G. Pearson Elementary School,NaN,Robinson,9195603988,colleen.robinson@dpsnc.net,10/28/2016 8:15,NaN,Durham,...,NaN,NaN,3501 Fayetteville St,NaN,96,Colleen,NaN,NaN,152.26.176.38,https://durhamnc.gov/FormCenter/Fire-Departmen...
791,35416.0,11/20/2017 14:10,NaN,NaN,Arrington,919-257-7013,eldner@nc.rr.com,12/16/2017 11:00,NaN,NaN,...,100 Kids Community March,NaN,"201 West Enterprise Street, Durham NC",We are trying to get at least 100 kids togethe...,135,Anne,Busting Loose Organization,Social or Community Group,45.37.104.64,http://durhamnc.gov/FormCenter/Fire-Department...
2532,112421.0,9/15/2023 8:15,NaN,NaN,Kuhns,9196360018,troop493leaders@gmail.com,10/6/2023 18:30,NaN,NaN,...,Girl Scout Troop 493 Tour,NaN,1818 Riddle Rd (Durham Fire Station 4),We are a Durham Girl Scout troop that would lo...,12,Rebecca,Girl Scouts-NC Coastal Pines,Social or Community Group,71.69.193.90,https://www.durhamnc.gov/FormCenter/Fire-Depar...
227,13169.0,4/19/2016 14:49,Ms. Annie's Preschool,NaN,Lewis,9199499800,annielewis83@gmail.com,5/5/2016 11:00,NaN,Durham,...,NaN,NaN,10 Queensland Ct,NaN,12,Annie,NaN,NaN,24.163.79.78,http://durhamnc.gov/FormCenter/Fire-Department...
835,40260.0,2/20/2018 18:05,NaN,NaN,Aviles,9194089181,Esmirnaviles@live.com,3/25/2018 11:00,NaN,NaN,...,Security specialist day,NaN,1606 Liberty St,We are a pathfinder and adventurer club for ki...,About 30 kids and 15 adults,Rosa,7th day Adventist Church,Church,66.87.133.73,http://durhamnc.gov/FormCenter/Fire-Department...
91,2269.0,10/8/2015 11:11,Durham Police Department,NaN,Walker,9199493649,Kimberle.Walker@durhamnc.gov,10/31/2015 11:00 AM to 10/31/2015 2:00 PM,NaN,Durham,...,NaN,NaN,1525 Glenn School Road (Walmart),NaN,NaN,Kimberle,NaN,NaN,70.61.92.170,http://durhamnc.gov/FormCenter/Fire-Department...
1972,78813.0,2/22/2022 13:06,NaN,NaN,Siesser,9199602834,billsiesser@gmail.com,3/13/2022 17:30,NaN,NaN,...,Cub Scout Visit to Parkwood Fire Department,NaN,1409 Seaton Rd,Chief Sloan and I have discussed having my cub...,12,Bill,"Cub Scout Pack 451, Wolf Den",Social or Community Group,136.226.50.182,https://durhamnc.gov/FormCenter/Fire-Departmen...
1774,66442.0,3/6/2021 16:54,NaN,NaN,Brooks,9195190220,emilycarolinern@gmail.com,3/7/2021 13:00,NaN,NaN,...,Birthday fun day,NaN,"3210, Ridgestone Parkway",Two boys birthdays! Age 6 and 8. We are having...,15,Emily,NaN,NaN,107.77.233.204,https://durhamnc.gov/FormCenter/Fire-Departmen...
165,9721.0,2/18/2016 16:20,Little River School,NaN,Byerly,919-943-0888,tidezin@hotmail.com,5/7/2016 10:00,NaN,Durham,...,NaN,NaN,2315 Snow Hill Rd,NaN,200,Tracy,NaN,NaN,75.189.151.130,http://nc-durham.civicplus.com/FormCenter/Fire...
2772,308051.0,5/20/2024 15:58,NaN,NaN,JOHNSTON,4046269254,johnston.sarah.d@gmail.com,7/4/2024 10:00,NaN,NaN,...,July 4th in Garrett Farms,NaN,"Cottonwood Dr, Durham NC",I am the Garrett Farms July 4th event coordina...,200,Sarah,NaN,Social or Community Group,107.15.131.220,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2678,298747.0,2/12/2024 21:39,NaN,NaN,Schumaker,9515267317,emma@lincolnavecap.com,2/22/2024 15:30,NaN,NaN,...,Family Resource Day at Avon Crossings,NaN,205 Kent Lake Dr,We are hosting a Family Resource Day for our r...,100,Emma,Avon Crossings Apartments,Government,76.89.80.145,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3449,371531.0,1/6/2026 15:01,NaN,NaN,Jackson,9193235073,Shannon.Jackson@duke.edu,2/28/2026 9:00,NaN,NaN,...,Car Seat Check Event,NaN,6919 Herndon Rd,We would like to host a car seat checking even...,25,Shannon,Safe Kids Durham County,Social or Community Group,174.245.115.186,https://www.durhamnc.gov/FormCenter/Fire-Depar...

In [570]:
print(df.columns.tolist())

['ID', 'Submission Date', 'Organization Name', 'Your First Name', 'Last Name', 'Phone Number', 'Email Address', 'Desired Date & Time of Event', 'Address of Event', 'City', 'State', 'Zip Code', 'Total Number of Children, Adults or both Participating in the Event', 'Fire Safety/Fire Prevention Programs', 'Additional Request or Questions?', 'Available Sations for Tour', 'Fire Safety/Fire Prevention Programs.1', 'Available Stations for Tour', 'Name of Event', 'End Time of the Event', 'Street Address of Event', 'Event Description', 'Anticipated Number of Participants', 'First Name', 'Agency Name', 'Type of Agency', 'IP Address', 'Referrer']

#### Data Cleaning

In [571]:
# Ensuring datetime type
df["Submission Date"] = pd.to_datetime(df["Submission Date"])

# Splitting into separate columns
df["Date of Submission"] = df["Submission Date"].dt.date.astype(str)   # YYYY-MM-DD
df["Time of Submission"] = df["Submission Date"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Submission Date"])

# Moving new columns to the front
cols = ["Date of Submission", "Time of Submission"] + [c for c in df.columns if c not in ["Date of Submission", "Time of Submission"]]
df = df[cols]

In [572]:
# Dropping unnecessary columns
df = df.drop(columns=["ID", "Your First Name", "Last Name", "Phone Number",
                     "Desired Date & Time of Event", "Address of Event", "City", "State", "Zip Code", 
                      "Total Number of Children, Adults or both Participating in the Event",
                     "Fire Safety/Fire Prevention Programs", "Additional Request or Questions?", 
                     "Available Sations for Tour", "Fire Safety/Fire Prevention Programs.1", "Available Stations for Tour", 
                     "End Time of the Event", "First Name", "IP Address", "Referrer", 
                      "Street Address of Event", "Organization Name", "Agency Name", "Type of Agency"])
display(df.sample(5))
print(df.columns.tolist())

,Date of Submission,Time of Submission,Email Address,Name of Event,Event Description,Anticipated Number of Participants
3156,2025-05-08,21:50:00,Kreativekidznc@gmail.com,Community Helpers Week,Community helpers week. Providing a visit for ...,9
2286,2023-01-17,10:03:00,ashley_turley@dpsnc.net,Kindergarten fire station visit,Kindergarten would like to tour Station 15 whi...,55
2870,2024-08-23,09:02:00,susie.palmieri@duke.edu,Wyndmoor at the Park NNO,NNO at Wyndmoor at the Park we have the event ...,130
3062,2025-02-13,18:59:00,takileak@gmail.com,Safety procedure and career training support a...,Hello my name is Taki Jamel Leak Bell and I wa...,1150
2858,2024-08-15,17:38:00,suthernkell@gmail.com,Shepherd's Flock Baptist Church Fall Festival,"Community event offering free food, clothing a...",100

['Date of Submission', 'Time of Submission', 'Email Address', 'Name of Event', 'Event Description', 'Anticipated Number of Participants']

In [573]:
# Converting to datetime safely
df["Date of Submission"] = pd.to_datetime(df["Date of Submission"], errors="coerce")

# Filtering only 2025 and 2026 rows (BEFORE any other operations)
df = df[df["Date of Submission"].dt.year.isin([2025, 2026])].copy()

# Sorting by date in descending order
df = df.sort_values("Date of Submission", ascending=False)


word_map = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4,
    "five": 5, "six": 6, "seven": 7, "eight": 8, "nine": 9,
    "ten": 10, "eleven": 11, "twelve": 12, "thirteen": 13,
    "fourteen": 14, "fifteen": 15, "sixteen": 16, "seventeen": 17,
    "eighteen": 18, "nineteen": 19, "twenty": 20,
    "thirty": 30, "forty": 40, "fifty": 50,
    "sixty": 60, "seventy": 70, "eighty": 80,
    "ninety": 90, "hundred": 100
}


def parse_word_number(text):
    t = text.strip().lower()
    return word_map.get(t, None)


def clean_participants(text):
    if pd.isna(text):
        return np.nan

    t = str(text).lower().replace(",", "").strip()

    nums = [float(x) for x in re.findall(r'\d+(?:\.\d+)?', t)]

    # Missing / invalid
    if not nums and not any(w in t for w in word_map):
        return np.nan

    # Homes excluded
    if "home" in t or "homes" in t:
        return np.nan

    # Word-only numbers
    word_num = parse_word_number(t)
    if word_num is not None:
        return float(word_num)

    # Over X
    over_pattern = re.search(r'\bover\s+(one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s*(hundred)?', t)
    if over_pattern:
        base = over_pattern.group(1)
        mult = over_pattern.group(2)

        value = float(base) if base.isdigit() else float(word_map.get(base, np.nan))
        if mult:
            value *= 100
        return value

    # Explicit total
    total = re.search(r'(\d+)\s*total', t)
    if total:
        return float(total.group(1))

    # STRICT CLASS RULE
    strict_class_pattern = re.search(r'^\s*(\d+)\s+\d+\s*classes', t)
    if strict_class_pattern:
        return float(strict_class_pattern.group(1))

    # Room range per class
    room_class_pattern = re.search(
        r'(\d+)\s*(?:to|-)\s*(\d+)\s*(?:children|kids|students).*?(\d+)\s*classes',
        t
    )
    if room_class_pattern:
        low = float(room_class_pattern.group(1))
        high = float(room_class_pattern.group(2))
        classes = float(room_class_pattern.group(3))
        return ((low + high) / 2) * classes

    # Classroom inference
    classroom_pattern = re.search(r'\d+\s*(classrooms|classes).*?(?:so|about).*?(\d+)', t)
    if classroom_pattern:
        return float(classroom_pattern.group(2))

    # Group ranges
    group_pattern = re.search(r'(\d+)\s*(groups|classes|sessions).*?(\d+)\s*(?:-|to)\s*(\d+)?', t)
    if group_pattern:
        groups = float(group_pattern.group(1))
        if group_pattern.group(4):
            low = float(group_pattern.group(3))
            high = float(group_pattern.group(4))
            return groups * ((low + high) / 2)
        return groups * float(group_pattern.group(3))

    # Slash values
    slash_pattern = re.findall(r'(\d+)\s*/\s*(\d+)', t)
    if slash_pattern:
        values = [np.mean([float(a), float(b)]) for a, b in slash_pattern]
        return np.mean(values)

    # FIX 1: 16 (1st round) 12 (2nd round) → average rounds
    if ("round" in t or "1st" in t or "2nd" in t):
        round_values = re.findall(r'\b(\d+)\s*\(', t)
        if len(round_values) >= 2:
            return np.mean([float(x) for x in round_values])

    # FIX 2: 35 3–5 year olds + 15 1–2 year olds → SUM (ONLY when both age groups exist)
    age_group_values = re.findall(r'(\d+)\s*(?:3\s*[-–]\s*5|1\s*[-–]\s*2|3-5|1-2|3–5|1–2|year|yr|yo|old)', t)

    # Critical: only trigger when there are clearly multiple groups
    if len(re.findall(r'\d+\s*(?:3\s*[-–]\s*5|3-5|1\s*[-–]\s*2|1-2)', t)) >= 2:
        return sum(float(x) for x in age_group_values if x.isdigit())

    # Role-based sums
    role_keywords = [
        "children", "kids", "adults", "students",
        "teachers", "parents", "boys", "girls"
    ]
    if any(k in t for k in role_keywords) and len(nums) > 1:
        return sum(nums)

    # Numeric ranges
    if re.search(r'\d+\s*-\s*\d+', t):
        pairs = re.findall(r'(\d+)\s*-\s*(\d+)', t)
        return np.mean([np.mean([float(a), float(b)]) for a, b in pairs])

    return nums[0]


# Applying cleaning
df["Participants_Clean"] = df["Anticipated Number of Participants"].apply(clean_participants)

# Splitting into yearly dataframes
df_2025 = df[df["Date of Submission"].dt.year == 2025].copy()
df_2026 = df[df["Date of Submission"].dt.year == 2026].copy()

# Renaming columns
for d in [df_2025, df_2026]:
    d.rename(columns={
        "Date of Submission": "Submission Date",
        "Time of Submission": "Submission Time"
    }, inplace=True)

#### Displaying Nan values in Participants_Clean

In [574]:
debug_df = df[df["Participants_Clean"].isna()][
    ["Anticipated Number of Participants", "Participants_Clean"]
]

display(debug_df)

     Anticipated Number of Participants  Participants_Clean
3553                                N/a                 NaN
3429                   Approx. 25 homes                 NaN
3209                                NaN                 NaN

#### Displaying count and samples

In [575]:
# Removing NaNs after cleaning
df_2025 = df_2025.dropna(subset=["Participants_Clean"])

# Row Count
display(f"2025 rows: {len(df_2025)}")

'2025 rows: 411'

In [576]:
display(df_2025.sample(60))

,Submission Date,Submission Time,Email Address,Name of Event,Event Description,Anticipated Number of Participants,Participants_Clean
3091,2025-03-12,11:35:00,gail.mccolgan@intusurg.com,World Safety Day,We are having the company's World Safety Day e...,100,100.0
3292,2025-08-30,15:07:00,edmundp.fernandez@gmail.com,The Tuscaloosa Lakewood Neighborhood Associati...,The Tuscaloosa Lakewood Neighborhood Associati...,60,60.0
3315,2025-09-10,12:44:00,qalston@fcrinc.org,Fire Safety/Fire Prevention Week in Classroom ...,"In our PreK classroom, we will be have a theme...",15,15.0
3327,2025-09-16,11:01:00,Antoinette_Daye@dpsnc.net,Fire Safety for Culinary Students,November is Career Development Month\r\nTeach ...,50,50.0
3391,2025-10-14,20:35:00,sastone676@gmail.com,Classroom visit,We are a nature based preschool with 14 kids a...,17,17.0
3347,2025-09-24,10:59:00,roger.vroom@gmail.com,Murray Massenburg Elementary Fall Festival,Fall Festival for Murray Massenburg students a...,500,500.0
3103,2025-03-20,16:31:00,KCoburn@MLTriangle.com,The Miracle League of the Triangle,The Miracle League of the Triangle is a non-pr...,210,210.0
3400,2025-10-21,11:47:00,latidaadams@gmail.com,Exploring all things with wheels & Safety,We are learning about transportation and all t...,8,8.0
3156,2025-05-08,21:50:00,Kreativekidznc@gmail.com,Community Helpers Week,Community helpers week. Providing a visit for ...,9,9.0
3408,2025-10-30,08:44:00,Earlyme860@Gmail.com,Fire station tour,Tour for 1 child ….he will be 6 in December,2,2.0
3387,2025-10-13,17:09:00,smithshae376@gmail.com,Fire Safety,Fire Safety and Prevention,75,75.0
3438,2025-11-24,12:52:00,greenspace@elfuturo-nc.org,Las Posadas,"Join us on Monday, December 15th at 5:30 PM fo...",200,200.0
3254,2025-08-13,14:26:00,Roseana.Matthews@durhamnc.gov,Trunk or Treat,Trunk or Treat event to hand out candy. Brink ...,400,400.0
3098,2025-03-19,13:57:00,susanne.bostian@iqvia.com,IQVIA Lab Week Extinguisher Training,lab / office personnel extinguisher training. ...,60,60.0
3088,2025-03-10,20:27:00,Trigby@cressetchristian.org,Easter Carnival,We are hosting a free community event to provi...,300,300.0
3135,2025-04-22,11:04:00,Lavernh@umrh.org,Fire Safety Day,We would like to have a Fire Truck to come to ...,35/40,37.5
3236,2025-07-25,11:21:00,kortni@wocconline.com,Back To School Drive,I’m reaching out on behalf of World Overcomers...,300,300.0
3195,2025-06-13,10:02:00,robert.ford@durhamnc.gov,Department of Water Management Safety Fair,The Department of Water Mangement will be hold...,100,100.0
3233,2025-07-23,15:11:00,nikki.graves@da.org,Durham Academy Preschool,"Hi,\r\n\r\nI would like to request a fire truc...",36,36.0
3395,2025-10-16,14:58:00,jevans_cmh@hotmail.com,Girl Scout troop meeting (First Aid badge),One of the requirements for the Junior First A...,12,12.0
3304,2025-09-03,22:09:00,loren.cone@lebanonvfd.org,LVFD Public Safety Day,"Saturday, October 18, 2025 from 12pm to 3pm. A...",100,100.0
3310,2025-09-05,13:03:00,directoratfps@gmail.com,Preschool Class visits/tours/experience at our...,Our 3-5 year old class would like to touch a f...,"35 3-5 year olds, 15 1-2 year olds in a separa...",50.0
3263,2025-08-18,08:48:00,elizabeth_reinstein@dpsnc.net,Oak Grove International Fall Fest,Our school is having our annual Fall Festival ...,100-200,150.0
3320,2025-09-12,18:44:00,Excelsiorptso@gmail.com,Excelsior Classical Academy fall festival,K-8 school fall festival to bring the school c...,300,300.0
3145,2025-04-30,23:06:00,kmsteeletx@gmail.com,Church Children’s Activity,"I am in charge of a boys activity at church, a...",15,15.0
3398,2025-10-20,11:49:00,jessicacr@kindbh.com,Trunk or Treat / Fall Fest,Kind Behavioral Health (KBH) in Durham is host...,30,30.0
3108,2025-03-28,13:50:00,jennifer_watson@dpsnc.net,Career Fair at City of Medicine Academy,This is a reschedule date from February for ou...,275,275.0
3151,2025-05-05,19:55:00,sarah.king@da.org,Durham Academy Summer Camp,We are a summer camp and would love to have a ...,76,76.0
3055,2025-02-11,11:54:00,robyn.m.neaville@gsk.com,2nd Annual Life Safety Day,2nd Annual GSK/Sodexo Life Safety Day Event - ...,20-25,22.5
3301,2025-09-03,10:05:00,michelle@primarycolorselc.com,Community Helpers -Fire Prevention,A brief presentation involving the firemen and...,70 children,70.0
3201,2025-06-23,12:49:00,mgyoung22@gmail.com,National Ice Cream Day,We’re hosting a community event at our LocoSho...,200,200.0
3396,2025-10-16,20:13:00,rajsandhu1971@yahoo.ca,Sikh Community Picnic,We are Sikh congregation and holding a special...,100-200,150.0
3389,2025-10-14,13:23:00,jessicah@earlystartacademy.com,ESA II Fire Safety Month,Early Start Academy II\r\nlocated in the back ...,40,40.0
3299,2025-09-02,17:29:00,sophia.eve.abram@gmail.com,Oren's 4th Birthday Party,Our son Oren is very passionate about fire tru...,120,120.0
3246,2025-08-06,18:45:00,cheresasimpson@gmail.com,National Night Out,We are requesting a visit with a vehicle for r...,150,150.0
3273,2025-08-22,11:43:00,pacarter52@gmail.com,National night out,National night out,150,150.0
3168,2025-05-18,12:29:00,joannemdunn@gmail.com,Falconbridge Neighborhood July 4th Parade,Neighborhood July 4th parade led by a fire tru...,Fifty,50.0
3099,2025-03-19,16:32:00,fundraising@lakewoodelementary.org,Bulldog Block Party & Wellness Fair,Lakewood Elementary is holding our 4th annual ...,300,300.0
3317,2025-09-11,10:02:00,elizabeth@thewoodcroftschoolnc.com,Woodcroft Fire Safety Day,We are a childcare center in Durham that cater...,50,50.0
3294,2025-09-02,09:24:00,gspkoffice@gmail.com,Preschool Firetruck visit,Preschool visit,16,16.0
3071,2025-02-24,12:45:00,Special.Washintgon@Kindercare.com,KinderCare Learning Center,Staying Safe,50,50.0
3185,2025-06-02,14:38:00,miller.tom2022@gmail.com,76th Annual Watts Hospital-Hillandale Neighbor...,This a short parade around two blocks in the W...,300-500,400.0
3353,2025-09-26,18:20:00,Stephenie_Pruett@dpsnc.net,Classroom Visit (PreK),Event is for Preschool Students at Sandy Ridge...,30,30.0
3123,2025-04-10,16:05:00,cburkhart@durhambulls.com,Durham Bulls Education Days 2025,Education days for kids,3500,3500.0
3134,2025-04-21,15:37:00,india_jiminez@dpsnc.net,Holt Elementary Career Day,Join us for Career Day and inspire the future!...,500,500.0
3217,2025-07-15,15:24:00,brightleaflifestyle@gmail.com,National Night Out,Partnership with the City of Durham Police Dep...,200,200.0
3402,2025-10-27,13:05:00,audra.carnes@actionbehavior.com,Touch-A-Truck Event,Event Name:\r\nAction Behavior Centers - Touch...,40,40.0
3113,2025-04-01,14:07:00,Lollipopkidscamp@gmail.com,Summer camp visit,Low income summer camp and wanted the kids to ...,30,30.0
3202,2025-06-23,13:27:00,arochez@nccu.edu,"Fire Safety, Residential Assistant Training",Educational training on fire safety on college...,90,90.0
3245,2025-08-06,09:34:00,chris@glass-jug.com,Durham Oktoberfest,Oktoberfest at Durham Central Park. Live music...,500,500.0
3413,2025-10-31,14:08:00,m0blife096@icloud.com,Fire drill education,Educating staff on proper fire drill procedure...,20-30,25.0
3046,2025-01-31,09:58:00,rhonda_brodie@dpsnc.net,WG Touch A Truck,We will be hosting another one for the 2024-20...,45,45.0
3335,2025-09-19,09:04:00,leonette_williams@dpsnc.net,Meeting our Community Helpers,We are studying community helpers and the stud...,20,20.0
3215,2025-07-15,05:19:00,busymom4god@yahoo.com,Lynn's Crossroads Ruritan Club Community Day,"All ages are invited to come have fun, fellows...",100 +,100.0
3346,2025-09-24,10:46:00,laura@wpcdurham.org,Community Helpers,Park by the front circle for preschools to com...,45,45.0
3373,2025-10-07,11:42:00,NaN,Fire Prevention/ Crime Prevention,"Come talk to the children about fire safety, t...",30,30.0
3064,2025-02-14,16:15:00,jsmith@are.com,ACLSD Fire Extinguisher Training,15 - 20 minute presentation with remaining tim...,50,50.0
3029,2025-01-06,09:52:00,jack.slavin@duke.edu,Duke Women's Basketball Hero Day,Duke Women's Basketball is hosting Hero Day on...,2000+,2000.0
3291,2025-08-29,16:06:00,Madison.Williams@durhamnc.gov,After School Classroom Visit,Would love to have a truck visit and to talk a...,15,15.0
3096,2025-03-18,13:09:00,kristinm_jones@dpsnc.net,Career Day,We have career day and I would like for all gr...,500,500.0

In [577]:
# Removing NaNs after cleaning
df_2026 = df_2026.dropna(subset=["Participants_Clean"])

# Row Count
display(f"2026 rows: {len(df_2026)}")

'2026 rows: 130'

In [578]:
display(df_2026.sample(60))

,Submission Date,Submission Time,Email Address,Name of Event,Event Description,Anticipated Number of Participants,Participants_Clean
3562,2026-05-04,09:35:00,emma@realityministries.org,Fire Station Tour,This event will be for Reality Ministries and ...,15,15.0
3464,2026-02-02,14:13:00,jsmith@are.com,Fire Extinguisher Training,Fire extinguisher training for ARE tenants. If...,25,25.0
3463,2026-02-02,14:10:00,jsmith@are.com,Fire Extinguisher Training,Fire extinguisher training for ARE tenants. If...,25,25.0
3558,2026-04-30,14:03:00,sdemeree@hotmail.com,North Street Neighborhood Pig Pickin',The pig pickin' will take place behind 819 Nor...,150,150.0
3578,2026-05-15,15:19:00,Teresa.Mendoza@durhamnc.gov,Touch A Truck,Durham Parks & Recreation Summer Camp,60,60.0
3521,2026-03-23,18:40:00,tomikasmall@gmail.com,Youth Explosion and Juneteenth Celebration,This annual event is an outreach fellowship fo...,100,100.0
3572,2026-05-14,15:58:00,brenda.jones@ratpdev.com,CPR - Hands Only,Request CPR Hands Only training for our employ...,15 - 20,17.5
3545,2026-04-19,19:42:00,ganyardwatch@gmail.com,Ganyard NNO,"Free food, music, games, prizes, vendors, and ...",100,100.0
3484,2026-02-25,11:26:00,ebony_brim-kinte@dpsnc.net,Ignite! Culture Fest,We are having a school wide (K-12) event for t...,25 students with a few adult bystanders,25.0
3482,2026-02-22,15:56:00,mitchellbrittney@outlook.com,Community Helpers Week,One of our preschool classes is learning about...,"The preschool class has 18 children, but we’d ...",18.0
3565,2026-05-06,13:03:00,mshunicutt@aol.com,Crystal Lake Fire Prevention & Safety Seminar,To educate and raise awareness of proper fire ...,50 - 75,62.5
3560,2026-05-01,09:51:00,candourhouse@greystar.com,Touch a Truck Event,Explain Grease Fires and bring a Truck for the...,60-80 people,70.0
3488,2026-02-27,10:41:00,judith_faggart@dpsnc.net,George Watts Montessori School\r\nClassroom Visit,Fire Safety for Pre-K and Kindergarten,100,100.0
3509,2026-03-15,12:51:00,Tachris@gap.com,Old Navy Safety Day,Every year Old Navy hosts a safety event and w...,50-100,75.0
3544,2026-04-16,20:48:00,whitneyeibl@gmail.com,Summer Block Party,We have a neighborhood block party at the begi...,150,150.0
3525,2026-03-25,10:58:00,bria@bookharvest.org,Book Harvest's Annual Summer Block Party,The afternoon will be filled with family activ...,3000,3000.0
3515,2026-03-18,17:52:00,Teresa_Hayes@dpsnc.net,Fire Extinguisher Training/Northern High Schoo...,Culinary students are in need of extinguisher ...,20-30,25.0
3535,2026-04-08,11:35:00,curtis_walker@dpsnc.net,"Walk, Bike and Roll to School Day","Walk, Bike and Roll Event, scheduled for Frida...",470,470.0
3489,2026-03-02,10:39:00,bryson_byrd@dpsnc.net,Primary Class Visits,Pre-K and Kindergarten Students will get to se...,144,144.0
3502,2026-03-09,11:36:00,elbert_smith@dpsnc.net,Y.E. Smith Elementary (Career Day),The event is Career Day for students in Pre-K ...,220 students total They will split into Groups,220.0
3570,2026-05-13,12:54:00,manager@southdurhamfarmersmarket.org,SoDu Anniversary at Hub RTP,Celebrate South Durham Farmers' Market's anniv...,300-400,350.0
3575,2026-05-14,16:08:00,brenda.jones@ratpdev.com,CPR - Hands Only Training,GoDurham requesting Hands-On Only CPR Training...,15 - 20,17.5
3486,2026-02-26,08:28:00,Katiehduke@gmail.com,Fire station tour,Family of 4 with 2 boys curious how firemen do...,4,4.0
3500,2026-03-07,11:34:00,fhgalberth@gmail.com,Grove Park Santa Parade,This is a parade that is led by the Fire Truck...,20-40,30.0
3501,2026-03-07,16:22:00,nursenikkisnewsnetwork@gmail.com,ABCs of Community Readiness,Subject: Invitation to Collaborate - LGBT+ BIP...,>100,100.0
3551,2026-04-25,06:07:00,Teresa_Hayes@dpsnc.net,Hazmat Decon Skills Demonstration,Northern's Fire Academy Level III students wil...,10,10.0
3567,2026-05-08,10:11:00,michelle_seabrook@dpsnc.net,First Grade Celebration,First Grade is having a celebration for all th...,80,80.0
3455,2026-01-13,12:43:00,jmalone@dha-nc.org,Staying Safe Together: Senior Safety & Evacuat...,We are requesting the Fire Department to visit...,40,40.0
3481,2026-02-20,06:20:00,Lauren.yarbrough@thelittleschool.net,The Investigators’ Little Heroes Day,\r\nOur Investigators are heading out for a sp...,60-90,75.0
3581,2026-05-16,12:45:00,Capricia_Johnsonammo@dpsnc.net,Fire Truck : Spring Valley Career Day Event: B...,Kindergarten Students are learning about Fire ...,88,88.0
3573,2026-05-14,16:05:00,brenda.jones@ratpdev.com,CPR Hands Only,GoDurham requesting Hands-On Only CPR Training...,15 - 20,17.5
3491,2026-03-03,12:14:00,kkblackwell152@gmail.com,Career Day,Career Day,2,2.0
3561,2026-05-01,16:52:00,gintas.juzumas@duke.edu,"Fire Extinguisher Training, Carmichael Building",On 10/5/26 at 9:15 AM we have scheduled Carmic...,30,30.0
3518,2026-03-20,16:14:00,Trigby@cressetchristian.org,Family Easter fun day,Church community outreach Easter carnival fun day,400-500,450.0
3494,2026-03-05,10:27:00,kristinm_jones@dpsnc.net,Career Day,Career Day- specific for our kindergarten stud...,200,200.0
3452,2026-01-12,13:59:00,carolineh@kingspark.org,Easter Fest,"Following our Easter services, King’s Park wil...","1,000",1000.0
3524,2026-03-24,17:07:00,candourhouse@greystar.com,Fire Safety Day,We would like to host a Fire Safety Event for ...,60-80 people,70.0
3520,2026-03-23,15:20:00,dlfonville@dconc.gov,Summer Reading Kickoff,This event is mostly for younger kids and thei...,100,100.0
3513,2026-03-18,01:18:00,hgsansone1956@gmail.com,Woodlake Independence Day parade,About 1/2 mile parade with adults and kids and...,100,100.0
3480,2026-02-19,18:07:00,mdevika@unc.edu,Fire Safety Workshop for Youth in Special Educ...,"My name is Devika, and I am a senior at UNC Ch...",27,27.0
3454,2026-01-13,12:05:00,eliza@msdurham.org,Montessori School of Durham Spring Fling,Montessori School of Durham Sping Fling - fami...,100,100.0
3477,2026-02-13,10:54:00,kathy_conner@dpsnc.net,CC Spaulding Elementary School Career Day,Career Day: Kindergarten and 1st Grade Studen...,3 groups of 35-45 students each,120.0
3538,2026-04-11,12:42:00,perry1angel@gmail.com,FCCI Health and Business Expo,Health information \r\nLine dance\r\nSmall bus...,15 - 20,17.5
3540,2026-04-14,09:52:00,April_Henderson@dpsnc.net,Touch a Truck,For 3 pre-k classes at Murray-Massenburg Eleme...,50,50.0
3541,2026-04-15,00:57:00,lwtwi2008@gmail.com,Life Center of Durham Annual Health Fair,The event is a community event that supported ...,300,300.0
3507,2026-03-11,12:36:00,kisha.dixon@kindercare.com,Staying Safe,"Our center will be talking about Staying Safe,...",42,42.0
3504,2026-03-09,17:06:00,fundraising@lakewoodelementary.org,Bulldog Block Party,Lakewood Elementary is hosting our fourth annu...,350,350.0
3554,2026-04-27,19:48:00,darlene.brannon525@gmail.com,Safety Week,Age 4 years old to 11 years old\r\nI want chil...,30,30.0
3467,2026-02-03,15:46:00,awunruh@gmail.com,George Watts Montessori Spring Carnival,George Watts Elementary serves kids in Pre-K t...,500,500.0
3563,2026-05-04,11:26:00,latoyabainea4@gmail.com,New Jerusalem's Family and friends Community Day,Our Community Day is a special event designed ...,75,75.0
3498,2026-03-06,14:17:00,Hellokitty320@gmail.com,FBLA Career Day,Future Business Leaders of America (FBLA) is h...,670 (rotating throughout the day),670.0
3510,2026-03-15,15:44:00,Teresa_Hayes@dpsnc.net,Hazmat Decon Practical Skills,We would like for the Hazmat Team to come to N...,10,10.0
3532,2026-04-01,14:27:00,evansnb@gmail.com,Logan’s 4th birthday party,This is the 4th birthday party for our daughte...,15 kids,15.0
3483,2026-02-24,09:18:00,anissa_hicklen@dpsnc.net,Career Day,Career Day \r\nWe would like the fire truck to...,80 4 classes with about 20 students per class,80.0
3537,2026-04-09,09:32:00,samantha.davey@duke.edu,"Dukes in Motion: Firefighter Day (hoses, gear,...","We will be having 20 kids, 20-25 volunteers, a...",20,20.0
3476,2026-02-12,23:14:00,vicepresident2@namidurham.org,"ALLIANCE HEALTH PRESENTS NAMI DURHAM MIND, BOD...","The NAMI Durham Mind, Body & Soul Wellness Exp...",200,200.0
3505,2026-03-09,20:12:00,megand.huggins@gmail.com,Springfest,Springfest: The neighbors of Chamberlynne are ...,75,75.0
3582,2026-05-18,11:39:00,dru@kidsrkidsrtp.com,Child Safety Week,Children will learn the basics of fire safety.,150,150.0
3566,2026-05-07,14:38:00,collinf@hopenorthcarolina.org,North Street Neighborhood Fire Station Tour,I would like to bring a small group of adults ...,12,12.0
3475,2026-02-12,10:46:00,nancy.holec@ymcatriangle.org,Healthy Kid Day,As we celebrate the YMCA’s 175 years of streng...,100,100.0

#### Output File Creation

In [579]:
# Joining 2025 and 2026 dataframes
df_final = pd.concat([df_2025, df_2026], ignore_index=True)

# Saving output to desktop folder
output_path = r"C:\Users\AmarachiOny\Desktop\DFD_Projects\Python\Captain_Burtons\output\cleaned_participants_data.csv"
df_final.to_csv(output_path, index=False)

# Displaying final row count
print("Final rows:", len(df_final))
print("Saved to:", output_path)

Final rows: 541
Saved to: C:\Users\AmarachiOny\Desktop\DFD_Projects\Python\Captain_Burtons\output\cleaned_participants_data.csv

In [ ]:
# File was editted manually afterwards