#### Importing Libraries

In [117]:
import pandas as pd
from IPython.display import display
import numpy as np
import os
import re

In [118]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Captain_Burtons/input/Akunna.csv")
display(df.sample(50))

,ID,Submission Date,Organization Name,Your First Name,Last Name,Phone Number,Email Address,Desired Date & Time of Event,Address of Event,City,...,Name of Event,End Time of the Event,Street Address of Event,Event Description,Anticipated Number of Participants,First Name,Agency Name,Type of Agency,IP Address,Referrer
1827,70742,6/27/2021 5:56,NaN,NaN,Zaffiri,7034624640,shivi4sai@yahoo.com,7/12/2021 10:00,NaN,NaN,...,Daycare visit for 2nd birthday,NaN,11 E bayberry ct,My son attends an in home daycare program in D...,10,shivi,NaN,NaN,99.92.51.182,https://durhamnc.gov/FormCenter/Fire-Departmen...
747,34832,10/2/2017 9:44,NaN,NaN,Teasley,9199495951,NaN,10/7/2017 14:00,NaN,NaN,...,Violence Awareness Event,4:00 PM,2944 Holloway Street,Community Event -,100,Joseph,New Life Family Worship,Church,70.61.92.170,http://durhamnc.gov/FormCenter/Fire-Department...
947,46089,6/6/2018 15:02,NaN,NaN,Schneider,919-237-2583,annecschneider@yahoo.com,8/7/2018 18:30,NaN,NaN,...,Grove Park Community Association National Nigh...,NaN,300 Nichols Farm Drive,Grove Park Community Association is an active ...,75,Anne,Grove Park Community Association,Social or Community Group,50.55.49.36,http://nc-durham.civicplus.com/FormCenter/Fire...
3053,335515,2/7/2025 8:18,NaN,NaN,Wiggins,919-471-1150,Special.Washintgon@Kindercare.com,7/3/2025 10:00,NaN,NaN,...,School-Age field trip,NaN,3919 N Duke Street,Bring our School-age group to do a fire statio...,25,Special,NaN,School,136.226.69.28,https://nc-durham.civicplus.com/FormCenter/Fir...
197,11515,3/22/2016 12:18,MAKIN' CHOICES INCORP.,NaN,ADAMS,919-490-8041,NaN,4/14/2016 13:00,NaN,DURHAM,...,NaN,NaN,2000 CHAPEL HILL ROAD SUITE 23,NaN,60,LAMONT,NaN,NaN,104.169.172.136,http://durhamnc.gov/FormCenter/Fire-Department...
1709,57526,8/28/2020 18:59,NaN,NaN,Royster,2027447771,anitra.goodman@gmail.com,8/30/2020 15:00,NaN,NaN,...,#TeamNoah Support Parade,NaN,2003 Copper Leaf Parkway,"Well wishes parade for my son, Noah, who is be...",25,Anitra,NaN,NaN,174.247.22.171,https://durhamnc.gov/FormCenter/Fire-Departmen...
592,32658,5/19/2017 9:56,Durham Hosiery Mills,NaN,Webb,919-680-8106,whykat@aol.com,6/14/2017 11:30,NaN,Durham,...,NaN,NaN,804 Angier Avenue,NaN,30,Kathy,NaN,NaN,174.194.19.33,http://nc-durham.civicplus.com/FormCenter/Fire...
2657,296698,1/18/2024 10:30,NaN,NaN,Loeser,919-225-2728,ltloeser@aol.com,2/3/2024 10:30,NaN,NaN,...,Loeser family firehouse tour,NaN,Fire station #2 tour (9th street),Brief tour for 3 related families and their 6 ...,9-Jun,Larry,NaN,NaN,174.109.113.17,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1053,47310,9/5/2018 12:14,NaN,NaN,Dillard,9194759357,carter.dillard39@yahoo.com,10/20/2018 15:00,NaN,NaN,...,Fix it Fest,NaN,4711 hope valley suite 1J,"We will be hosting Ace hardware's Fix-it-Fest,...",roughly 50-150,Carter,Triangle Ace Hardware,Business,24.106.185.134,http://nc-durham.civicplus.com/FormCenter/Fire...
434,23377,10/11/2016 13:39,World Overcomers Christian Church Children's M...,NaN,Wynn,704-957-1644,patricia@wocconline.org,10/29/2016 14:00,NaN,Durham,...,NaN,NaN,2933 South Miami Blvd,NaN,"3,000",Patricia,NaN,NaN,24.106.191.122,https://durhamnc.gov/FormCenter/Fire-Departmen...
150,8853,2/3/2016 11:52,Rand-Whitney,NaN,Keeler-Smart,919-973-6039,ZKeelerSmart@randwhitney.com,2/26/2016 13:00,NaN,Durham,...,NaN,NaN,3829 S. Miami Blvd,NaN,12,Zackary,NaN,NaN,70.62.112.170,http://durhamnc.gov/FormCenter/Fire-Department...
3428,366276,11/11/2025 13:21,NaN,NaN,Hardy,919-741-2151,timothy.hardy@ceva.com,2/18/2026 10:00,NaN,NaN,...,fire extinguisher training,NaN,1717 east lawson st,basic fire extinguisher training,25,Timothy,Ceva,Business,70.60.236.26,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1734,59801,10/2/2020 14:54,NaN,NaN,Nicholson,91948909700,s.nicholson.cps@gmail.com,10/22/2020 10:45,NaN,NaN,...,Drive by Parade for Fire Safety Month,NaN,1912 Chapel Hill Rd,"Drive by ""parade"" in our parking lot. Classroo...",30 children,Samantha,Community Preschool,School,107.13.146.109,https://durhamnc.gov/FormCenter/Fire-Departmen...
1974,78975,2/25/2022 14:54,NaN,NaN,Williams,919-560-2890,frances_williams@dpsnc.net,4/12/2022 9:00,NaN,NaN,...,Spring Valley Elementary Career Day,NaN,2051 Northern Durham Pkwy,Presentation for kindergarten and 1st grade st...,150,Frances,Spring Valley Elementary,School,152.22.48.27,https://www.durhamnc.gov/FormCenter/Fire-Depar...
209,12350,4/5/2016 17:12,Royal Rangers,NaN,Gard,9192064800,mgard99@gmail.com,4/27/2016 19:30,NaN,Durham,...,NaN,NaN,A City of Durham Fire Station,NaN,15-Dec,Matthew,NaN,NaN,168.244.4.55,http://durhamnc.gov/FormCenter/Fire-Department...
598,32798,5/26/2017 12:02,"Spoken-4 Communications, LLC",NaN,Ramsey,919-361-1090,tierre.ramsey@spoken-4.com,7/1/2017 13:00,NaN,Durham,...,NaN,NaN,1801 Fayettville Street,NaN,250,Tierre,NaN,NaN,107.13.152.12,https://durhamnc.gov/FormCenter/Fire-Departmen...
729,34702,9/22/2017 13:40,NaN,NaN,Williams,9198067782,dlwilliams1052@gmail.com,10/14/2017 11:00,NaN,NaN,...,Morehead Avenue Baptist Church Community Healt...,1:00 PM,1008 Morehead Avenue,Wellness Ministry at Morehead Avenue Baptist C...,100-125 (Church staff will assist all vendors),Donna,Morehead Avenue Baptist Church,Church,75.189.206.57,https://durhamnc.gov/FormCenter/Fire-Departmen...
1761,64668,1/14/2021 7:57,NaN,NaN,Bandiera,919-653-2572,tj.bandiera@trianglerestores.org,2/10/2021 8:00,NaN,NaN,...,Habitat ReStore Fire Extinguisher Training,NaN,2121 TW Alexander Dr,Fire Extinguisher Training,12-Oct,T. J.,Habitat ReStore,Business,66.195.223.214,https://durhamnc.gov/FormCenter/Fire-Departmen...
1948,75042,11/7/2021 14:07,NaN,NaN,John,19194754450,Alexis.John@durhamnc.gov,11/30/2021 16:00,NaN,NaN,...,Commity Outreach,NaN,1101 E. Lawson St.,Community Outreach and share a message on fire...,100,A.,Neighborhood Improvement,Government,45.37.88.5,https://durhamnc.gov/FormCenter/Fire-Departmen...
1331,50390,5/21/2019 7:04,NaN,NaN,Hughes,919-407-0392,hughesmallori86@gmail.com,6/28/2019 18:30,NaN,NaN,...,Kyles Temple AME Zion Church Family Block Party,NaN,409 Dunstan Ave,Ending our Vacation Bible School week. Having ...,50-75,Mallori,NaN,Church,76.182.106.84,https://durhamnc.gov/FormCenter/Fire-Departmen...
3069,336910,2/24/2025 9:59,NaN,NaN,Pruitt,9194520212,selenapruitt@kestrelheights.org,3/28/2025 9:00,NaN,NaN,...,Kestrel Heights Charter School's Career Day,NaN,"4700 South Alston Ave. Durham, NC",Career Day for K-5 students at Kestrel Heights...,120 (not all at once),Selena,Kestrel Heights Charter School,School,152.26.235.178,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1935,74717,10/27/2021 9:28,NaN,NaN,Hunt,9195597154,Jhunt_919@aol.com,11/6/2021 15:00,NaN,NaN,...,Hunt Block Party,NaN,2601 Hillsborough Rd,Block party/Birthday Party Touch the truck eve...,15,Jonathan,Hunt Group,Social or Community Group,107.115.17.24,https://durhamnc.gov/FormCenter/Fire-Departmen...
198,11520,3/22/2016 13:41,MAKIN' CHOICES INC.,NaN,ADAMS,919-490-8041,makinchoices05@yahoo.com,4/14/2016 13:00,NaN,Durham,...,NaN,NaN,2000 Chapel Hill Road,NaN,60,LAMONT,NaN,NaN,104.169.172.136,http://durhamnc.gov/FormCenter/Fire-Department...
116,3956,11/4/2015 9:59,The Scrap Exchange,NaN,Brush,9196822751,operations@scrapexchange.org,12/9/2015 10:00 AM to 12/9/2015 11:00 AM,NaN,Durham,...,NaN,NaN,2050 Chapel Hill Rd.,NaN,12,Phoebe,NaN,NaN,50.124.133.212,http://durhamnc.gov/FormCenter/Fire-Department...
3176,345828,5/23/2025 9:36,NaN,NaN,Osborn,9194107868,ross@triangleultimate.org,7/18/2025 18:00,NaN,NaN,...,Southeast Social,NaN,"632 N Hoover Rd, Durham, NC","Join us on Friday, July 18th from 6:00–7:30pm ...",100,Ross,Triangle Ultimate,Business,136.56.180.169,https://www.durhamnc.gov/FormCenter/Fire-Depar...
3438,367517,11/24/2025 12:52,NaN,NaN,Gomez,9845281094,greenspace@elfuturo-nc.org,12/15/2025 17:30,NaN,NaN,...,Las Posadas,NaN,2020 Chapel Hill Rd #23,"Join us on Monday, December 15th at 5:30 PM fo...",200,Dorian,El Futuro,Social or Community Group,204.85.209.206,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1509,52347,9/27/2019 12:59,NaN,NaN,Fullard,9199373737,Chauntefullard@yahoo.com,10/8/2019 10:15,NaN,NaN,...,Fire prevention week,NaN,212 Davidson Avenue Durham NC,"Hello, we would like to have the firetruck and...",200 ( children and teachers across the centers),Chaunte,A New Beginning,School,24.163.61.196,https://durhamnc.gov/FormCenter/Fire-Departmen...
1787,67350,4/6/2021 14:01,NaN,NaN,Memije,9195603906,eric_memije@dpsnc.net,5/5/2021 9:00,NaN,NaN,...,Brogden Middle School Career Day,NaN,1001 Leon St,We are looking for career panelists to help wi...,60,Owen,Durham Public Schools,School,198.85.255.10,https://durhamnc.gov/FormCenter/Fire-Departmen...
466,25618,12/6/2016 22:33,Pearsontown Elementary School kindergartners,NaN,Januzzi,919-724-5231,paula.januzzi-godfre@dpsnc.net,2/27/2017 10:00,NaN,Durham,...,NaN,NaN,139 E. MORGAN STREET,NaN,70 (split into four groups),Paula,NaN,NaN,45.37.161.80,https://durhamnc.gov/FormCenter/Fire-Departmen...
329,18711,7/18/2016 16:58,Durham Head Start,NaN,Glenn,919-219-4863,cglenn@durhamhs.org,8/24/2016 9:00,NaN,Durham,...,NaN,NaN,215 W. Seminary St.,NaN,12 to 15,Wayne,NaN,NaN,24.142.227.134,http://nc-durham.civicplus.com/FormCenter/Fire...
2236,86840,10/22/2022 11:15,NaN,NaN,Saxton,919-623-6375,Saxtons1967@gmail.com,11/5/2022 11:00,NaN,NaN,...,Triangle Church Fall Festival,NaN,2103 Page Rd.,Our church's annual fall festival (That was re...,800,Jackie,Triangle Church,Church,38.132.129.201,https://www.durhamnc.gov/FormCenter/Fire-Depar...
489,28127,2/1/2017 15:44,Woodcroft Swim and Tennis Club,NaN,Canning,9194897705,activities@woodcroftclub.org,4/29/2017 11:00,NaN,Durham,...,NaN,NaN,1203 W. Woodcroft Parkway,NaN,500,Jessica,NaN,NaN,76.182.34.138,http://durhamnc.gov/FormCenter/Fire-Department...
496,28511,2/9/2017 10:41,Little River K-8 School: Kindergarten Classes,NaN,McBride,9197046182,laura.mcbride@dpsnc.net,3/8/2017 11:45,NaN,Durham,...,NaN,NaN,2060 Torredge Road,NaN,"58 students, 5 adults",Laura,NaN,NaN,152.26.176.38,https://durhamnc.gov/FormCenter/Fire-Departmen...
2472,108210,7/31/2023 20:32,NaN,NaN,Delagrammatikas,9084770244,christaldelas@gmail.com,8/19/2023 21:30,NaN,NaN,...,Awareness Run/Walk- Spritz 'n' Sprint for Mala...,NaN,8306 NC-751,Awareness and charitable event for a child wit...,50,Christal,St. Barbara Greek Orthodox Church,Church,107.15.215.80,https://www.durhamnc.gov/FormCenter/Fire-Depar...
781,35188,10/30/2017 9:55,NaN,NaN,Ramero,9195969511,marketing@ragingbullhd.com,11/11/2017 10:30,NaN,NaN,...,Dont Text & Drive,3:00 PM,300 Muldee Street,Raise awareness of the dangers of texting and ...,??,Oliver,Raging Bull Harley-Davidson,Business,66.57.203.98,http://durhamnc.gov/FormCenter/Fire-Department...
711,34580,9/15/2017 9:41,NaN,NaN,Overton,9198627033,kavanoverton@yahoo.com,10/18/2017 10:00,NaN,NaN,...,DECI,10:45 AM,1717 E Lawson Street,Its a Day Program that work with adults with d...,30,Kavan,DECI,Business,70.60.99.26,https://durhamnc.gov/FormCenter/Fire-Departmen...
1671,54974,5/14/2020 12:29,NaN,NaN,Davis,6128607020,chelseardavis84@gmail.com,6/15/2020 12:00,NaN,NaN,...,Daily’s 5th birthday,NaN,917 Alabama Ave,Our daughter Daily is turning 5 and we were wo...,4,Chelsea,NaN,Social or Community Group,174.109.74.8,https://durhamnc.gov/FormCenter/Fire-Departmen...
86,2138,10/7/2015 8:40,"Cree, Inc.",NaN,Botts,(919) 407-5322,joshua.botts@cree.com,11/19/2015 10:30 AM to 11/19/2015 11:30 AM,NaN,Durham,...,NaN,NaN,4600 Silicon Drive,NaN,Estimated to be around 25,Josh,NaN,NaN,8.42.18.10,http://durhamnc.gov/FormCenter/Fire-Department...
957,46356,6/21/2018 11:41,NaN,NaN,Cole-McFadden,910 614-4756,africancora@aol.com,8/18/2018 11:00,NaN,NaN,...,Youth Explosion,NaN,1901 Athens Street,community youth celebration,50,Cora,West Durham Baptist Church,Church,50.111.44.47,http://nc-durham.civicplus.com/FormCenter/Fire...
2182,85986,9/26/2022 10:58,NaN,NaN,White,919-425-9180,janaewhite49@gmail.com,10/19/2022 10:30,NaN,NaN,...,Fire Prevention Month @ Croasdaile Village,NaN,2600 Croasdaile Farm Parkway,Senior Citizen Event\r\nThey are all wheelchai...,10-20ppl,Janae,Croasdaile Village,Business,155.130.130.200,https://www.durhamnc.gov/FormCenter/Fire-Depar...
157,9421,2/11/2016 16:14,lakeview missionary baptist church,NaN,evans,919.308373,kwashington9@nc.rr.com,3/26/2016 10:00,NaN,durham,...,NaN,NaN,3411 dearborn dr.,NaN,100,karen,NaN,NaN,50.111.63.114,http://nc-durham.civicplus.com/FormCenter/Fire...
2239,86946,10/25/2022 12:58,NaN,NaN,Johnson,9195604296,amanda.johnson@durhamnc.gov,2/25/2023 12:00,NaN,NaN,...,PLAYMORE with Us at River Forest Park,NaN,"1000 Windermere Dr, Durham, NC",PLAYMORE with Us at River Forest Park. Grab yo...,50,Amanda,DPR - Walltown Park Recreation Center,Government,66.195.223.214,https://www.durhamnc.gov/FormCenter/Fire-Depar...
2252,87402,11/4/2022 12:47,NaN,NaN,Ellis,9194918637,csellis@hotmail.com,12/10/2022 0:00,NaN,NaN,...,Greysons Green and Greycliff Christmas Parade,NaN,Southern High School Football Stadium Parking Lot,This is our community's 7th annual community C...,150,Craig,Greysons Green Rec Association,Social or Community Group,172.124.107.141,https://www.durhamnc.gov/FormCenter/Fire-Depar...
1613,53984,2/5/2020 15:33,NaN,NaN,evans,9193083730,kwashington9@nc.rr.com,4/11/2020 10:00,NaN,NaN,...,family and friends day,NaN,3411 dearborn drive,"this event is for the church and community, it...",150,karen,lakeview missionary baptist church,Church,98.26.40.108,https://durhamnc.gov/FormCenter/Fire-Departmen...
1177,48229,11/28/2018 8:17,NaN,NaN,Baker,9198800929,Parroth701@aol.com,12/9/2018 13:00,NaN,NaN,...,American Legion Murdock Christmas Party,NaN,406 E Trinity Ave,Bring Santa Clause into parking lot of the Ame...,30,Randy,American Legion,Social or Community Group,152.16.191.68,http://nc-durham.civicplus.com/FormCenter/Fire...
1898,73841,9/28/2021 11:18,NaN,NaN,Lochansky,919-560-4384,NICOLE.LOCHANSKY@DURHAMNC.GOV,10/26/2021 8:00,NaN,NaN,...,North Durham Fire Extinguisher Training,NaN,1900 E. Club Blvd-North Durham- WRF,We need to conduct our annual Fire Extinguishe...,15,Nicole,Water Management-North,Government,74.219.16.122,https://durhamnc.gov/FormCenter/Fire-Departmen...
1247,49413,3/8/2019 9:44,NaN,NaN,Sam,919-724-5481,jean_marie_sam@hotmail.com,3/26/2019 9:30,NaN,NaN,...,Miss Mollie's Preschool Fireman/woman Visit,NaN,824 N Buchanan Blvd,"Speak to preschoolers about fire safety, sit i...",17,Jean,NaN,School,174.109.115.246,https://durhamnc.gov/FormCenter/Fire-Departmen...
2646,292910,12/18/2023 11:59,NaN,NaN,Thompson,4084779873,alison.thompson@analog.com,2/27/2024 9:30,NaN,NaN,...,Fire Extinguisher Training for the Workplace E...,NaN,4001 NC Hwy 54 Suite 3100,The fire extinguisher training is intended on ...,20,Alison,"Analog Devices, Inc.",Business,204.17.143.20,https://www.durhamnc.gov/FormCenter/Fire-Depar...
973,46503,6/30/2018 15:04,NaN,NaN,Price,407-715-1746,pricelinda1959@yahoo.com,7/16/2018 10:00,NaN,NaN,...,Daycare Visit,NaN,100 Wittenburg Way,I want to teach the preschoolers that the fire...,20 including teachers,Linda,21st Centure Preschool,School,107.13.137.101,http://durhamnc.gov/FormCenter/Fire-Department...
987,46664,7/10/2018 15:48,NaN,NaN,Gualtieri,919-226-1521,erickag@durhamcoke.com,8/14/2018 8:30,NaN,NaN,...,Fire Drill - Durham Coca-Cola,NaN,3214 Hillsborough Road Durham NC,I would like to have a mock fire drill for our...,60+,Ericka,Durham Coca-Cola Bottling Company,Business,209.155.84.98,http://nc-durham.civicplus.com/FormCenter/Fire...

In [119]:
print(df.columns.tolist())

['ID', 'Submission Date', 'Organization Name', 'Your First Name', 'Last Name', 'Phone Number', 'Email Address', 'Desired Date & Time of Event', 'Address of Event', 'City', 'State', 'Zip Code', 'Total Number of Children, Adults or both Participating in the Event', 'Fire Safety/Fire Prevention Programs', 'Additional Request or Questions?', 'Available Sations for Tour', 'Fire Safety/Fire Prevention Programs.1', 'Available Stations for Tour', 'Name of Event', 'End Time of the Event', 'Street Address of Event', 'Event Description', 'Anticipated Number of Participants', 'First Name', 'Agency Name', 'Type of Agency', 'IP Address', 'Referrer']

#### Data Cleaning

In [120]:
# Ensuring datetime type
df["Submission Date"] = pd.to_datetime(df["Submission Date"])

# Splitting into separate columns
df["Date of Submission"] = df["Submission Date"].dt.date.astype(str)   # YYYY-MM-DD
df["Time of Submission"] = df["Submission Date"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Submission Date"])

# Moving new columns to the front
cols = ["Date of Submission", "Time of Submission"] + [c for c in df.columns if c not in ["Date of Submission", "Time of Submission"]]
df = df[cols]

In [121]:
# Dropping unnecessary columns
df = df.drop(columns=["ID", "Your First Name", "Last Name", "Phone Number", "Email Address",
                     "Desired Date & Time of Event", "Address of Event", "City", "State", "Zip Code", 
                      "Total Number of Children, Adults or both Participating in the Event",
                     "Fire Safety/Fire Prevention Programs", "Additional Request or Questions?", 
                     "Available Sations for Tour", "Fire Safety/Fire Prevention Programs.1", "Available Stations for Tour", 
                     "End Time of the Event", "First Name", "IP Address", "Referrer", "Event Description", 
                      "Street Address of Event"])
display(df.sample(5))
print(df.columns.tolist())

,Date of Submission,Time of Submission,Organization Name,Name of Event,Anticipated Number of Participants,Agency Name,Type of Agency
1215,2019-02-11,11:54:00,NaN,Family Day at Kidcycle NC,250-300,Diaper Bank of NC,Social or Community Group
502,2017-02-16,14:25:00,National Institute of Environmental Health and...,NaN,50 Adults,NaN,NaN
2362,2023-03-31,11:47:00,NaN,Foster Home Inspection,2,NaN,Social or Community Group
3432,2025-11-14,11:47:00,NaN,E. K. Powe Early Release Day Fun Day,100,E. K. Powe Elementary,Social or Community Group
518,2017-03-05,10:24:00,Durham VA Medical Center,NaN,1,NaN,NaN

['Date of Submission', 'Time of Submission', 'Organization Name', 'Name of Event', 'Anticipated Number of Participants', 'Agency Name', 'Type of Agency']

In [122]:
# Removing rows where date looks like "10-May", "14-Jul", etc. (no year present originally)
df = df[~df["Date of Submission"].astype(str).str.match(r'^\d{1,2}-[A-Za-z]{3}$', na=False)]

# Converting to datetime safely
df["Date of Submission"] = pd.to_datetime(df["Date of Submission"], errors="coerce")

# Filtering only 2025 and 2026 rows (BEFORE any other operations)
df = df[df["Date of Submission"].dt.year.isin([2025, 2026])].copy()

# Sorting by date in descending order
df = df.sort_values("Date of Submission", ascending=False)


def clean_participants(text):
    if pd.isna(text):
        return np.nan

    t = str(text).lower().replace(",", "")

    nums = [float(x) for x in re.findall(r'\d+(?:\.\d+)?', t)]
    if not nums:
        return np.nan
    
    # PRIORITY: "X classrooms so about Y children" → take Y only
    classroom_total_pattern = re.search(
        r'\d+\s*(classrooms|classes).*?(?:so|about).*?(\d+)',
        t
    )
    if classroom_total_pattern:
        return float(classroom_total_pattern.group(2))
    
    # PRIORITY 1: explicit total
    total = re.search(r'(\d+)\s*total', t)
    if total:
        return float(total.group(1))

    # PRIORITY 2: X classes/groups with Y per class
    class_pattern = re.search(r'(\d+)\s*classes.*?(?:about\s*)?(\d+)\s*(?:students|people|kids|per class|each)?', t)
    if class_pattern:
        return float(class_pattern.group(1)) * float(class_pattern.group(2))

    # PRIORITY 3: X groups/classes of Y-Z
    group_pattern = re.search(r'(\d+)\s*(groups|classes|sessions).*?(\d+)\s*(?:-|to)\s*(\d+)?', t)
    if group_pattern:
        groups = float(group_pattern.group(1))
        if group_pattern.group(4):
            low = float(group_pattern.group(3))
            high = float(group_pattern.group(4))
            return groups * ((low + high) / 2)
        return groups * float(group_pattern.group(3))

    # PRIORITY 4: slash values like 35/40 → average
    if "/" in t and len(nums) >= 2:
        return np.mean(nums)

    # PRIORITY 5: ranges like 50-75
    if re.search(r'\d+\s*-\s*\d+', t):
        pairs = re.findall(r'(\d+)\s*-\s*(\d+)', t)
        return np.mean([np.mean([float(a), float(b)]) for a, b in pairs])

    # PRIORITY 6: role-based sums (kids, parents, etc.)
    role_keywords = ["children", "kids", "adults", "students", "teachers", "parents", "boys", "girls"]
    if any(k in t for k in role_keywords) and len(nums) > 1:
        return sum(nums)

    # PRIORITY 7: over days → ignore extra context
    if "over" in t and "day" in t:
        return max(nums)

    return nums[0]


# Applying cleaning
df["Participants_Clean"] = df["Anticipated Number of Participants"].apply(clean_participants)

# Removing NaNs AFTER cleaning
df = df.dropna(subset=["Participants_Clean"])


# Splitting into yearly dataframes
df_2025 = df[df["Date of Submission"].dt.year == 2025].copy()
df_2026 = df[df["Date of Submission"].dt.year == 2026].copy()


# Renaming columns
for d in [df_2025, df_2026]:
    d.rename(columns={
        "Date of Submission": "Submission Date",
        "Time of Submission": "Submission Time"
    }, inplace=True)

#### Displaying samples

In [123]:
display(f"2025 rows: {len(df_2025)}")

'2025 rows: 418'

In [124]:
display(df_2025.sample(65))

,Submission Date,Submission Time,Organization Name,Name of Event,Anticipated Number of Participants,Agency Name,Type of Agency,Participants_Clean
3370,2025-10-06,10:14:00,NaN,Trick-or-Treat Jamboree,400,Grey Stone Church,Church,400.0
3071,2025-02-24,12:45:00,NaN,KinderCare Learning Center,50,NaN,School,50.0
3330,2025-09-16,13:13:00,NaN,Fall Festival,50,New Life Child Development Center,School,50.0
3166,2025-05-15,14:46:00,NaN,Community Helpers Week,60,Durham Parks and Rec School Age Care,Government,60.0
3298,2025-09-02,17:01:00,NaN,Intersession Camp,100,Community Education/ Pearsontown Elementary,School,100.0
...,...,...,...,...,...,...,...,...
3229,2025-07-21,12:35:00,NaN,NCSSM Reunion,20-40,NCSSM,School,30.0
3392,2025-10-15,14:36:00,NaN,Trunk or Treat,50,The Little Gym or Durham,Business,50.0
3096,2025-03-18,13:09:00,NaN,Career Day,500,Murray Massenburg,School,500.0
3135,2025-04-22,11:04:00,NaN,Fire Safety Day,35/40,Croasdaile Village,Business,37.5
3105,2025-03-27,10:19:00,NaN,School Wide Visit/ Safety week,135,First Environments Early Learning Center,School,135.0

In [125]:
display(f"2026 rows: {len(df_2026)}")

'2026 rows: 135'

In [126]:
display(df_2026.sample(65))

,Submission Date,Submission Time,Organization Name,Name of Event,Anticipated Number of Participants,Agency Name,Type of Agency,Participants_Clean
3507,2026-03-11,12:36:00,NaN,Staying Safe,42,KinderCare,School,42.0
3541,2026-04-15,00:57:00,NaN,Life Center of Durham Annual Health Fair,300,Life Center,Social or Community Group,300.0
3584,2026-05-19,17:32:00,NaN,77th Annual Watts-Hillandale July 4 Parade and...,400,Watts Hospital-Hillandale Neighborhood Associa...,Social or Community Group,400.0
3495,2026-03-05,16:37:00,NaN,Fire Safety - PASS Training,40,Voltage Energy,Business,40.0
3574,2026-05-14,16:07:00,NaN,Hands-On Only CPR,15 - 20,GoDurham,Business,17.5
...,...,...,...,...,...,...,...,...
3506,2026-03-10,12:29:00,NaN,Fire Extinguisher Training for FF I Students,16 (1st round) 12 (2nd round),Durham Public Schools / Northern High School,School,16.0
3464,2026-02-02,14:13:00,NaN,Fire Extinguisher Training,25,"Alexandria Real Estate Equities, Inc.",Business,25.0
3576,2026-05-15,15:13:00,NaN,Walltown Summer Camp,30,NaN,Government,30.0
3491,2026-03-03,12:14:00,NaN,Career Day,2,Leo's Foundation Academy,School,2.0
3452,2026-01-12,13:59:00,NaN,Easter Fest,"1,000",King's Park International Church,Church,1000.0

#### Dropping rows with 10-May, 15-Jul, etc. in Anticipated Number of Participants column